<div class="container"><?php var_dump($area);die();?>
    <div class="content-header" data-area-identifier="area-content_header">
        <?=$this->partial('content/area', array(
            'area' => $area['content_header'],
        ));?>
    </div><!-- /.content-header -->
    <div class="row">
        <div class="col-sm-12 content-main content-full" data-area-identifier="area-content_main">
            <?=$this->partial('content/area', array(
                'area' => $area['content_main'],
            ));?>
        </div><!-- /.content-main -->
    </div><!-- /.row -->
</div><!-- /.container -->
<footer class="content-footer footer-main" data-area-identifier="area-footer_main">
    <?=$this->partial('content/area', array(
        'area' => $area['footer_main'],
    ));?>
</footer><!-- /.content-footer -->