<?php

$form->prepare();

?>

<?=$this->form()->openTag($form);?>

<?=$this->formElementErrors($form->get('application_id'));?>
<?=$this->formElementErrors($form->get('csrf'));?>
<?=$this->formInput($form->get('form_update')->get('fieldset_petition')->get('uid'));?>
<?=$this->formInput($form->get('form_update')->get('fieldset_petition')->get('application_uid'));?>
<?=$this->formInput($form->get('form_update')->get('fieldset_petition')->get('site_uid'));?>
<?=$this->formInput($form->get('form_update')->get('fieldset_petition_translation')->get('uid'));?>
<?=$this->formInput($form->get('form_update')->get('fieldset_petition_translation')->get('petition_uid'));?>

<?=$this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('uid'));?>
<?=$this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('application_uid'));?>
<?=$this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('site_uid'));?>
<?=$this->formElementErrors($form->get('form_update')->get('fieldset_petition_translation')->get('uid'));?>
<?=$this->formElementErrors($form->get('form_update')->get('fieldset_petition_translation')->get('petition_uid'));?>


<div class="row">
    <div class="col-12 py-2 px-0">
        <h3 class="display-5"><?=$this->translate("Some basic information about your Petition");?></h3>
    </div>
</div>

<div class="row">
    <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
        <?=$this->formLabel($form->get('form_update')->get('fieldset_petition')->get('name'));?>
    </div>
    <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('name'))))?'has-errors':'';?>">
        <?=$this->formInput($form->get('form_update')->get('fieldset_petition')->get('name'));?>
        <?=$this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('name'));?>
    </div>
    <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
        <small><?=$this->translate('This name will be visible only by you and other registered users.');?></small>
    </div>
</div>

<div class="row">
    <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
        <?=$this->formLabel($form->get('form_update')->get('fieldset_petition')->get('name_global'));?>
    </div>
    <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('name_global'))))?'has-errors':'';?>">
        <?=$this->formInput($form->get('form_update')->get('fieldset_petition')->get('name_global'));?>
        <?=$this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('name_global'));?>
    </div>
    <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
        <small><?=$this->translate('This name will be visible on global listings.');?></small>
    </div>
</div>

<div class="row">
    <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
        <?=$this->formLabel($form->get('form_update')->get('fieldset_petition')->get('country'));?>
    </div>
    <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('country'))))?'has-errors':'';?>">
        <?=$this->formSelect($form->get('form_update')->get('fieldset_petition')->get('country'));?>
        <?=$this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('country'));?>
    </div>
    <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
        <small><?=$this->translate('Tell us the country where your petition will be held.');?></small>
    </div>
</div>

<div class="row">
    <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
        <?=$this->formLabel($form->get('form_update')->get('fieldset_petition')->get('group'));?>
    </div>
    <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('group'))))?'has-errors':'';?>">
        <?=$this->formSelect($form->get('form_update')->get('fieldset_petition')->get('group'));?>
        <?=$this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('group'));?>
    </div>
    <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
        <small><?=$this->translate('This name will be present to users from other countries than yours.');?></small>
    </div>
</div>

<div class="row">
    <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
        <?=$this->formLabel($form->get('form_update')->get('fieldset_petition')->get('status'));?>
    </div>
    <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('status'))))?'has-errors':'';?>">
        <?=$this->formSelect($form->get('form_update')->get('fieldset_petition')->get('status'));?>
        <?=$this->formElementErrors($form->get('form_update')->get('fieldset_petition')->get('status'));?>
    </div>
    <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
        <small><?=$this->translate('Would you like to publish your Petition straight away or review it first?');?></small>
    </div>
</div>

<hr />



<?=$this->form()->closeTag();?>

