
    <div class="app-container app-template-read border-3">
        <div class="app-container-content p-4 p-md-5">

            <div class="app-container-header">
                <?=$this->partial("common-admin-partial::partial-header",['heading'=>$data_template_model['heading'],'data'=>$resources]);?>
            </div>

            <hr />

            <?php if($resources): ?>
                <?php foreach($resources['list'] as $res): var_dump($res['service_config']['partial']); ?>
                    <?php  if(array_key_exists('partial',$res['service_config'])): ?>
                        <?php $this->partial($res['service_config']['partial'],['resource'=>$res]);?>
                    <?php  endif;?>
                <?php endforeach;?>

            <?php endif; ?>

        </div>
    </div>
