<?php if ($this->pageCount): ?>
    <nav aria-label="Pages">
        <ul class="pagination justify-content-center">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class="page-item">
                    <a class="page-link" href="<?=$this->url($this->route, array('page' => $this->previous)); ?>">&lt; Previous</a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="<?=$this->url($this->route, array('page' => $this->previous)); ?>">&lt; Previous</a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li class="page-item">
                        <a class="page-link" href="<?=$this->url($this->route, array('page' => $page)); ?>"><?=$page;?></a>
                    </li>
                <?php else: ?>
                    <li class="page-item active">
                        <a class="page-link" href="<?=$this->url($this->route, array('page' => $page)); ?>"><?=$page;?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next &gt;</a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="<?=$this->url($this->route, array('page' => $this->next)); ?>">Next &gt;</a>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
<?php endif; ?>
