<?php

$form->prepare();

?>

<?=$this->form()->openTag($form);?>

<?=$this->formElementErrors($form->get('application_id'));?>
<?=$this->formElementErrors($form->get('csrf'));?>

<div>
    <div class="container-fluid pt-2">

        <div class="row">
            <div class="col-12 col-md-10 py-2 text-justify">
                <p>On this Page you will be able to add the new Pirate Material.</p>
            </div>
            <div class="col-12 col-md-2 py-2 text-right">
                <?=$this->formSubmit($form->get('submit'));?>
            </div>
            <div class="col-12 py-2">
                <hr />
            </div>
        </div>

            <?=$this->formInput($form->get('form_update')->get('fieldset_entry_item')->get('uid'));?>
            <?=$this->formElementErrors($form->get('form_update')->get('fieldset_entry_item')->get('uid'));?>

            <?=$this->formInput($form->get('form_update')->get('fieldset_yt_entry_item')->get('uid'));?>
            <?=$this->formElementErrors($form->get('form_update')->get('fieldset_yt_entry_item')->get('uid'));?>

            <?=$this->formInput($form->get('form_update')->get('fieldset_yt_entry_item')->get('parent_uid'));?>
            <?=$this->formElementErrors($form->get('form_update')->get('fieldset_yt_entry_item')->get('parent_uid'));?>

            <?=$this->formInput($form->get('form_update')->get('fieldset_yt_entry_item')->get('status'));?>
            <?=$this->formElementErrors($form->get('form_update')->get('fieldset_yt_entry_item')->get('status'));?>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_entry_item')->get('status'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_entry_item')->get('status'))))?'has-errors':'';?>">
                <?=$this->formSelect($form->get('form_update')->get('fieldset_entry_item')->get('status'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_entry_item')->get('status'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Set the Status for the Entry Item.');?></small>
            </div>
            <div class="col-12 py-2">
                <hr />
            </div>
        </div>

        <div class="row">
            <div class="col-12 py-2">
                <h3 class="display-5"><?=$this->translate("Some basic information about your Pirate Material");?></h3>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_yt_entry_item')->get('title'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_yt_entry_item')->get('title'))))?'has-errors':'';?>">
                <?=$this->formInput($form->get('form_update')->get('fieldset_yt_entry_item')->get('title'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_yt_entry_item')->get('title'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('This name will be visible by everyone.');?></small>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_yt_entry_item')->get('yt_id'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_yt_entry_item')->get('yt_id'))))?'has-errors':'';?>">
                <?=$this->formInput($form->get('form_update')->get('fieldset_yt_entry_item')->get('yt_id'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_yt_entry_item')->get('yt_id'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Tell us the YouTube ID.');?></small>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_entry_item')->get('comm'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_entry_item')->get('comm'))))?'has-errors':'';?>">
                <?=$this->formInput($form->get('form_update')->get('fieldset_entry_item')->get('comm'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_entry_item')->get('comm'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('This name will be visible only for admins.');?></small>
            </div>
        </div>

        <hr />
        <div class="py-2 px-3 mb-2">
            <?=$this->formSubmit($form->get('submit'));?>
        </div>

        <div class="hidden">
            <?=$this->formElement($form->get('application_id'));?>
            <?=$this->formElement($form->get('csrf'));?>
        </div>

    </div>
</div>

<?=$this->form()->closeTag();?>

