<?php if(array_key_exists($this->currentLanguage(),$petition['petition']['data']['translation']) && false!==$petition['petition']['data']['translation'][$this->currentLanguage()]): ?>
    <?php $translation = $petition['petition']['data']['translation'][$this->currentLanguage()]; ?>
<?php elseif(array_key_exists($this->defaultLanguage(),$petition['petition']['data']['translation'])): ?>
    <?php $translation = $petition['petition']['data']['translation'][$this->defaultLanguage()]; ?>
<?php else: ?>
    <?php $translation = $petition['petition']['data']['translation'][0]; ?>
<?php endif; ?>

<h1><?=$this->markdown($translation->getTitle());?></h1>

<div class="row">
    <div class="col-12 col-md-8 order-4 order-md-0">
        <hr class="d-block d-md-none" />
        <?=$this->markdown($translation->getText());?>
    </div>
    <div class="col-12 col-md-4">
        <div class="float-right mb-4">
            <a class="twitter-share-button"
               href="https://twitter.com/intent/tweet?text=Hello%20world"
               data-size="large">
                Tweet</a>
            <div class="fb-share-button" style="top:-8px;" data-href="https://peticio.art13.eu" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fpetycja.art13.eu%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Partager</a></div>

        </div>

        <?php if( isset($form) && array_key_exists('request',$form['form'])): ?>
            <h3><?=$this->markdown($this->translate("Signature has been recorded."));?></h3>
            <p><?=$this->markdown($this->translate("Thank you for your support!"));?></p>
        <?php elseif(isset($form)): ?>
            <?=$this->getFormAttached($form['form'],null,'data',true,'petition::petition-form-sign');?>
        <?php endif;?>
        <hr class="d-block d-md-none" />
    </div>
</div>




