<div class="container slide-home" data-area-identifier="area-004">
    <div class="row">
        <div class="col-md-4">
            <div data-block-identifier="block-005">
                <div id="carousel-home-narrow" class="carousel slide" data-ride="carousel">
                    <?php
                    echo $this->partial('content/area', array(
                        'area' => $area['elearning_course_not_started'],
                    ));
                    ?>
                <div class="clearfix hr-20" data-block-identifier="#"></div>
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-home-narrow" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-home-narrow" data-slide-to="1"></li>
                        <li data-target="#carousel-home-narrow" data-slide-to="2"></li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div id="carousel-home-wide" class="carousel slide pause" data-ride="carousel">
                <script>$('#carousel-home-wide').carousel({
                        interval: 200000000
                    })</script>
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#carousel-home-wide" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-home-wide" data-slide-to="1"></li>
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">



                    <div class="item active">
                        <div class="row">
                            <div class="clearfix hr-20" data-block-identifier="#"></div>
                            <div class="col-sm-6 block-cosntent" data-block-identifier="block-#" style="background-color:#296aa4">
                                <div class="row">
                                    <div class="col-sm-4 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <img src="/assets/img/thumb-006.png" alt="" class="img-responsive">
                                    </div>
                                    <div class="col-sm-8 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <h6 style="color: #ccf131;">Module</h6>
                                        <p><a href="/conference/report/123" style="'color:#fff">Patient communication and psychology</a></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 block-contsent" data-block-identifier="block-#" style="background-color:#296aa4">
                                <div class="row">
                                    <div class="col-sm-4 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <img src="/assets/img/thumb-006.png" alt="" class="img-responsive">
                                    </div>
                                    <div class="col-sm-8 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <div>
                                            <h6 style="color: #ccf131;">Module</h6>
                                            <p style="'color:#fff"><a href="/conference/report/123" style="'color:#fff">Orlando Magic: report from the 57th meeting of the American Society of Haematology, 5-7 December 2015, Orlando, USA</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="clearfix hr-20" data-block-identifier="#"></div>
                            <div class="col-sm-6 block-cosntent" data-block-identifier="block-#" style="background-color:#296aa4">
                                <div class="row">
                                    <div class="col-sm-4 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <img src="/assets/img/thumb-006.png" alt="" class="img-responsive">
                                    </div>
                                    <div class="col-sm-8 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <h6 style="color: #ccf131;">Module</h6>
                                        <p><a href="/conference/report/123">Orlando Magic: report from the 57th meeting of the American Society of Haematology, 5-7 December 2015, Orlando, USA</a></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 block-contsent" data-block-identifier="block-#" style="background-color:#296aa4">
                                <div class="row">
                                    <div class="col-sm-4 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <img src="/assets/img/thumb-006.png" alt="" class="img-responsive">
                                    </div>
                                    <div class="col-sm-8 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <div>
                                            <h6 style="color: #ccf131;">Module</h6>
                                            <p><a href="/conference/report/123">Orlando Magic: report from the 57th meeting of the American Society of Haematology, 5-7 December 2015, Orlando, USA</a></p>


                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="clearfix hr-20" data-block-identifier="#"></div>
                            <div class="col-sm-6 block-cosntent" data-block-identifier="block-#" style="background-color:#296aa4">
                                <div class="row">
                                    <div class="col-sm-4 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <img src="/assets/img/thumb-006.png" alt="" class="img-responsive">
                                    </div>
                                    <div class="col-sm-8 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <h6 style="color: #ccf131;">Module</h6>
                                        <p><a href="/conference/report/123">Orlando Magic: report from the 57th meeting of the American Society of Haematology, 5-7 December 2015, Orlando, USA</a></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 block-contsent" data-block-identifier="block-#" style="background-color:#296aa4">
                                <div class="row">
                                    <div class="col-sm-4 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <img src="/assets/img/thumb-006.png" alt="" class="img-responsive">
                                    </div>
                                    <div class="col-sm-8 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                                        <div>
                                            <h6 style="color: #ccf131;">Module</h6>
                                            <p><a href="/conference/report/123">Orlando Magic: report from the 57th meeting of the American Society of Haematology, 5-7 December 2015, Orlando, USA</a></p>


                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Research:</h5>
                                            <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix hr-20" data-block-identifier="block-#"></div>
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-007.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Case Report:</h5>
                                            <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Research:</h5>
                                            <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix hr-20" data-block-identifier="block-#"></div>
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-007.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Case Report:</h5>
                                            <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Research:</h5>
                                            <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
                                        </div>
                                    </div>
                                    <div class="clearfix hr-5" data-block-identifier="block-#"></div>
                                </div>
                                <div class="clearfix hr-20" data-block-identifier="block-#"></div>
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-007.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Case Report:</h5>
                                            <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Left and right controls -->
                <a class="left carousel-control" href="#carousel-home-wide" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-home-wide" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <div class="clearfix hr-20" data-block-identifier="#"></div>
</div>
<?php
//echo $this->partial('content/area', array(
//    'area' => $area['elearning_course_not_started'],
//));
?>
<div class="container" data-area-identifier="area-006">
    <div class="row">
        <div class="col-sm-6 block-header" data-block-identifier="block-#">
            <h2 data-content-identifier="content-#">Tags</h2>
        </div>




        <div class="col-sm-6 block-header" data-block-identifier="block-#">
            <h2 data-content-identifier="content-#">Our Support</h2>
        </div>
        <div class="clearfix hr-5" data-block-identifier="block-#"></div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">Tags</div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">???</div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <img data-content-identifier="content-#" src="/assets/img/logo/logo-ecco-001.jpg" alt="" class="img-responsive" />
            </div>
        </div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <img data-content-identifier="content-#" src="/assets/img/logo/logo-ecco-001.jpg" alt="" class="img-responsive" />
            </div>
        </div>
        <div class="clearfix hr-5" data-block-identifier="block-#"></div>
        <div class="clearfix hr-5" data-block-identifier="block-#"></div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#"></div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#"></div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <img data-content-identifier="content-#" src="/assets/img/logo/logo-ecco-001.jpg" alt="" class="img-responsive" />
            </div>
        </div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <img data-content-identifier="content-#" src="/assets/img/logo/logo-ecco-001.jpg" alt="" class="img-responsive" />
            </div>
        </div>
    </div>
</div>
<div class="jumbotron" data-area-identifier="area-007">
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1" data-block-identifier="block-#">
                <img src="/assets/img/img-011.png" alt="" class="img-responsive" />
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12" data-block-identifier="block-#" style="background-color:#fff">
                <h2>e-learning for oncology professionals</h2>
                <div class="col-sm-3">
                    <img src="/assets/img/img-012.png" alt="" class="img-responsive" />
                </div>
                <div class="col-sm-9">
                    <p>ecancer provides e-learning courses for fee to the oncology community.</p>
                    <p>Our resources cover a variety of topics and have been developed in partnership with leading organisations and individuals. Oue e-larning is impactful and focuses on the end goal of improving patient care and outcomes.</p>
                    <p>Our resources are completely free of charge; all we ask is that you register for the ecancer club so that we are able to record our learning.</p>
                    <div class="clearfix hr-20"></div>
                    <button type="button" class="btn btn-success pull-right">Success</button>
                </div>
            </div>
        </div>
    </div>
</div>