<div class="jumbotron">
    <?php echo $this->partial('content/area', array(
        'area' => $area['jumbotron_001'],
    )); ?>
</div>

<?php echo $this->partial('content/area', array(
    'area' => $area['content_001'],
)); ?>

<?php echo $this->partial('content/area', array(
    'area' => $area['quotes_001'],
)); ?>

<div class="clearfix hr-20"></div>
<div class="clearfix hr-20"></div>
<div class="clearfix hr-20"></div>

<div class="jumbotron">
    <?php echo $this->partial('content/area', array(
        'area' => $area['contact_001'],
    )); ?>
</div>



