<div class="container slide-home" data-area-identifier="area-004">
    <div class="row">
        <div class="col-md-4">
            <div data-block-identifier="block-005">
                <div id="carousel-home-narrow" class="carousel slide" data-ride="carousel">
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <div class="embed-responsive embed-responsive-16by9">
                                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/u7K72X4eo_s" frameborder="0" allowfullscreen></iframe>
                            </div>
                            <div>
                                <ul>
                                    <li>
                                        <label>Published:</label>
                                        <span>13.11.15</span>
                                    </li>
                                    <li>
                                        <label>Views:</label>
                                        <span>245</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="carousel-narrow-caption">
                                <div data-block-identifier="block-#">
                                    <h4>Video Report:</h4>
                                    <p>Treatment strategies and options in castration - resistant and advanced prostate cancer</p>
                                    <p>Audrey Mailor and Ian Lewis</p>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="embed-responsive embed-responsive-16by9">
                                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/u7K72X4eo_s" frameborder="0" allowfullscreen></iframe>
                            </div>
                            <div>
                                <ul>
                                    <li>
                                        <label>Published:</label>
                                        <span>13.11.15</span>
                                    </li>
                                    <li>
                                        <label>Views:</label>
                                        <span>245</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="carousel-narrow-caption">
                                <div data-block-identifier="block-#">
                                    <h4>Video Report:</h4>
                                    <p>Treatment strategies and options in castration - resistant and advanced prostate cancer</p>
                                    <p>Audrey Mailor and Ian Lewis</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-home-narrow" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-home-narrow" data-slide-to="1"></li>
                        <li data-target="#carousel-home-narrow" data-slide-to="2"></li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div id="carousel-home-wide" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#carousel-home-wide" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-home-wide" data-slide-to="1"></li>
                    <li data-target="#carousel-home-wide" data-slide-to="2"></li>
                    <li data-target="#carousel-home-wide" data-slide-to="3"></li>
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Research:</h5>
                                            <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-007.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Case Report:</h5>
                                            <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div>
                                    <div class="row carousel-inner-item carousel-item-wrapper">
                                        <div class="col-md-3">
                                            <img src="/assets/img/thumb-005.png" alt="" class="img-responsive" />
                                        </div>
                                        <div class="col-md-9">
                                            <div class="carousel-item-wrapper-text narrow">
                                                <h5>Research:</h5>
                                                <p class="block-text">Orlando Magic: report from the 57th meeting of the American Society of Haematology, 5-7 December 2015, Orlando, USA</p>
                                            </div>
                                        </div>
                                        <div class="clearfix hr-10" data-block-identifier="#"></div>
                                    </div>
                                    <div class="clearfix hr-10" data-block-identifier="#"></div>
                                    <div class="row carousel-inner-item carousel-item-wrapper">
                                        <div class="col-md-3">
                                            <img src="/assets/img/thumb-006.png" alt="" class="img-responsive" />
                                        </div>
                                        <div class="col-md-9">
                                            <div class="carousel-item-wrapper-text narrow">
                                                <h5>ECCO News:</h5>
                                                <p class="block-text">EVENTS: EBCC10 - Controversial issues in radiotherapy treatment ind in surgery</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix hr-10" data-block-identifier="#"></div>
                                    <div class="row carousel-inner-item carousel-item-wrapper">
                                        <div class="col-md-3">
                                            <img src="/assets/img/thumb-004.png" alt="" class="img-responsive" />
                                        </div>
                                        <div class="col-md-9">
                                            <div class="carousel-item-wrapper-text narrow">
                                                <h5>Case Report:</h5>
                                                <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="row">
                            <div class="col-sm-6">
                                <div>
                                    <div class="row carousel-inner-item carousel-item-wrapper">
                                        <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" />
                                        <h5>Research:</h5>
                                        <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
                                    </div>
                                </div>
                                <div>
                                    <div>
                                        <img src="/assets/img/thumb-007.png" alt="" class="img-responsive" />
                                        <h5>Case Report:</h5>
                                        <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div>
                                    <div class="row carousel-inner-item carousel-item-wrapper">
                                        <div class="col-md-3">
                                            <img src="/assets/img/thumb-005.png" alt="" class="img-responsive" />
                                        </div>
                                        <div class="col-md-9">
                                            <h5>Research:</h5>
                                            <p class="block-text">Orlando Magic: report from the 57th meeting of the American Society of Haematology, 5-7 December 2015, Orlando, USA</p>
                                        </div>
                                    </div>
                                    <div class="clearfix hr-10" data-block-identifier="#"></div>
                                    <div class="row carousel-inner-item carousel-item-wrapper">
                                        <div class="col-md-3">
                                            <img src="/assets/img/thumb-006.png" alt="" class="img-responsive" />
                                        </div>
                                        <div class="col-md-9">
                                            <h5>ECCO News:</h5>
                                            <p class="block-text">EVENTS: EBCC10 - Controversial issues in radiotherapy treatment ind in surgery</p>
                                        </div>
                                    </div>
                                    <div class="clearfix hr-10" data-block-identifier="#"></div>
                                    <div class="row carousel-inner-item carousel-item-wrapper">
                                        <div class="col-md-3">
                                            <img src="/assets/img/thumb-004.png" alt="" class="img-responsive" />
                                        </div>
                                        <div class="col-md-9">
                                            <h5>Case Report:</h5>
                                            <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Left and right controls -->
                <a class="left carousel-control" href="#carousel-home-wide" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-home-wide" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <div class="clearfix hr-20" data-block-identifier="#"></div>
</div>
<div class="container" data-area-identifier="area-005">
    <div class="row">
        <div class="col-sm-12 block-header" data-block-identifier="block-#">
            <h2>Top Stories</h2>
        </div>
        <div class="clearfix hr-5" data-block-identifier="block-#"></div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3>Headline</h3>
                <div class="content">
                    <p>Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper. Nunc felis libero, tincidunt quis quam eu, faucibus finibus purus. Ut luctus porttitor lorem non aliquet.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3>A longer headline</h3>
                <img src="/assets/img/thumb-010.png" alt="" class="img-responsive" />
                <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
            </div>
        </div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3>Even longer headline</h3>
                <p class="block-text">Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper. Nunc felis libero, tincidunt quis quam eu, faucibus finibus purus. Ut luctus porttitor lorem non aliquet.</p>
            </div>
        </div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3>Headline with video</h3>
                <!-- 16:9 aspect ratio -->
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/u7K72X4eo_s" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container" data-area-identifier="area-006">
    <div class="row">
        <?php echo $this->partial('content/area', array(
            'area' => $area['most_popular_area'],
        ));
        ?>
        <div class="col-sm-12 block-header" data-block-identifier="block-#">
            <h2 data-content-identifier="content-#">Most Popular</h2>
        </div>
        <div class="clearfix hr-5" data-block-identifier="block-#"></div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3 data-content-identifier="content-#">Headline</h3>
                <div class="content">
                    <p>Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper. Nunc felis libero, tincidunt quis quam eu, faucibus finibus purus. Ut luctus porttitor lorem non aliquet.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 block-item wide" data-block-identifier="block-#">
            <div class="block-content-item-wrapper">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-0 wrapper-inner" data-block-identifier="block-#">
                        <h3 data-content-identifier="content-#">A longer headline</h3>
                        <p data-content-identifier="content-#" class="block-text">Praesent consectetur rutrum erat. Praesent dictum facilisis nibh at venenatis. Cras nec ante feugiat, lacinia mi in, dictum nulla. Nam congue pharetra justo eget interdum. Pellentesque aliquet, dolor at tempor rhoncus, libero orci pellentesque magna, sed rutrum massa lectus eget metus. Ut venenatis vulputate leo in accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque felis a odio sodales porttitor.</p>
                    </div>
                    <div class="col-sm-6" data-block-identifier="block-#">
                        <img data-content-identifier="content-#" src="/assets/img/img-010.png" alt="" class="img-responsive" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3 data-content-identifier="content-#">Headline with video</h3>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/u7K72X4eo_s" frameborder="0" allowfullscreen></iframe>
                </div>
                <div>
                    <p>Ut luctus porttitor lorem non aliquet. Donec in turpis ac tortor pharetra suscipit. Sed varius risus mattis, convallis urna id, facilisis nunc.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="jumbotron" data-area-identifier="area-007">
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1" data-block-identifier="block-#">
                <img src="/assets/img/img-011.png" alt="" class="img-responsive" />
            </div>
        </div>
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1" data-block-identifier="block-#">
                <h2>e-learning for oncology professionals</h2>
                <div class="col-sm-3">
                    <img src="/assets/img/img-012.png" alt="" class="img-responsive" />
                </div>
                <div class="col-sm-9">
                    <p>ecancer provides e-learning courses for fee to the oncology community.</p>
                    <p>Our resources cover a variety of topics and have been developed in partnership with leading organisations and individuals. Oue e-larning is impactful and focuses on the end goal of improving patient care and outcomes.</p>
                    <p>Our resources are completely free of charge; all we ask is that you register for the ecancer club so that we are able to record our learning.</p>
                    <div class="clearfix hr-20"></div>
                    <button type="button" class="btn btn-success pull-right">Success</button>
                </div>
            </div>
        </div>
    </div>
</div>