

<?php echo $this->partial('content/area', array(
    'area' => $area['video_editor_choice'],
));

$blocks = $area['video_editor_choice']->getBlock();



?>



<div class="container" data-area-identifier="area-005">
    <div class="row">
        <div class="col-sm-12 block-header" data-block-identifier="block-#">
            <h2>Editor's choice</h2>
        </div>
        <div class="clearfix hr-5" data-block-identifier="block-#"></div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3>Headline</h3>
                <div class="content">
                    <p>Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper. Nunc felis libero, tincidunt quis quam eu, faucibus finibus purus. Ut luctus porttitor lorem non aliquet.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3>A longer headline</h3>
                <img src="/assets/img/thumb-010.png" alt="" class="img-responsive" />
                <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
            </div>
        </div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3>Even longer headline</h3>
                <p class="block-text">Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper. Nunc felis libero, tincidunt quis quam eu, faucibus finibus purus. Ut luctus porttitor lorem non aliquet.</p>
            </div>
        </div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3>Headline with video</h3>
                <!-- 16:9 aspect ratio -->
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/u7K72X4eo_s" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="http://open.http.mp.streamamg.com/p/243/sp/24300/embedIframeJs/uiconf_id/30013881/partner_id/243?autoembed=true&entry_id=0_398uckdm&playerId=kaltura_player_1456314852&cache_st=1456314852&width=&height="></script>
<div class="container" data-area-identifier="area-006">
    <div class="row">
        <div class="col-sm-12 block-header" data-block-identifier="block-#">
            <h2 data-content-identifier="content-#">Videos by Conference</h2>
        </div>
        <div class="clearfix hr-5" data-block-identifier="block-#"></div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3 data-content-identifier="content-#">Headline</h3>
                <div class="content">
                    <p>Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper. Nunc felis libero, tincidunt quis quam eu, faucibus finibus purus. Ut luctus porttitor lorem non aliquet.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 block-item wide" data-block-identifier="block-#">
            <div class="block-content-item-wrapper">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-0 wrapper-inner" data-block-identifier="block-#">
                        <h3 data-content-identifier="content-#">A longer headline</h3>
                        <p data-content-identifier="content-#" class="block-text">Praesent consectetur rutrum erat. Praesent dictum facilisis nibh at venenatis. Cras nec ante feugiat, lacinia mi in, dictum nulla. Nam congue pharetra justo eget interdum. Pellentesque aliquet, dolor at tempor rhoncus, libero orci pellentesque magna, sed rutrum massa lectus eget metus. Ut venenatis vulputate leo in accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque felis a odio sodales porttitor.</p>
                    </div>
                    <div class="col-sm-6" data-block-identifier="block-#">
                        <img data-content-identifier="content-#" src="/assets/img/img-010.png" alt="" class="img-responsive" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3 data-content-identifier="content-#">Headline with video</h3>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/u7K72X4eo_s" frameborder="0" allowfullscreen></iframe>
                </div>
                <div>
                    <p>Ut luctus porttitor lorem non aliquet. Donec in turpis ac tortor pharetra suscipit. Sed varius risus mattis, convallis urna id, facilisis nunc.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="jumbotron" data-area-identifier="area-007">
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1" data-block-identifier="block-#">
                <img src="/assets/img/img-011.png" alt="" class="img-responsive" />
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12" data-block-identifier="block-#" style="background-color:#fff">
                <h2>e-learning for oncology professionals</h2>
                <div class="col-sm-3">
                    <img src="/assets/img/img-012.png" alt="" class="img-responsive" />
                </div>
                <div class="col-sm-9">
                    <p>ecancer provides e-learning courses for fee to the oncology community.</p>
                    <p>Our resources cover a variety of topics and have been developed in partnership with leading organisations and individuals. Oue e-larning is impactful and focuses on the end goal of improving patient care and outcomes.</p>
                    <p>Our resources are completely free of charge; all we ask is that you register for the ecancer club so that we are able to record our learning.</p>
                    <div class="clearfix hr-20"></div>
                    <button type="button" class="btn btn-success pull-right">Success</button>
                </div>
            </div>
        </div>
    </div>
</div>