<div class="container" data-area-identifier="area-004">
    <div class="clearfix hr-20" data-block-identifier="#"></div>
    <div class="row">
        <div class="col-md-8">
            <?php echo $this->partial('content/area', array(
                'area' => $area['video_item'],
            ));
            ?>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div style="width:50%;display:inline-block;background-color:#709dc7;text-align:center;">
                    <h4 style="color: #ccf131;">Views</h4>
                    <span style="font-size:2.1em;color:#fff;">10,000</span>
                    <div class="clearfix hr-20" data-block-identifier="#"></div>
                </div>
                <div style="width:50%;float:left;background-color:#709dc7;text-align:center;">
                    <h4 style="color: #ccf131;">Shares</h4>
                    <span style="font-size:2.1em;color:#fff;">40</span>
                    <div class="clearfix hr-20" data-block-identifier="#"></div>
                </div>
                <div class="clearfix hr-20" data-block-identifier="#"></div>
            </div>
            <div class="row">
                <div class="col-sm-12" style="color:#fff;width:100%;display:inline-block;background-color:#6e757f;text-align:left;">
                    <h4><span>Share</span><span class="glyphicon glyphicon-share pull-right" aria-hidden="true"></span></h4>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-d12 block-header" data-block-identifier="block-#">
                    <h2>Related Content</h2>
                </div>
                <div class="col-sm-d12 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                    <div class="embed-responsive embed-responsive-16by9">
                        <script src="http://open.http.mp.streamamg.com/p/243/sp/24300/embedIframeJs/uiconf_id/30013881/partner_id/243?autoembed=true&amp;entry_id=0_398uckdm&amp;playerId=kaltura_player_1456314852&amp;cache_st=1456314852&amp;width=&amp;height="></script><div id="kaltura_player_1456314852" class="kWidgetIframeContainer kWidgetIframeContainer kWidgetIframeContainer" style="width: 400px; height: 330px; overflow: hidden;"><iframe id="kaltura_player_1456314852_ifp" scrolling="no" name="kaltura_player_1456314852_ifp" class="mwEmbedKalturaIframe" aria-labelledby="Player kaltura_player_1456314852" aria-describedby="The Kaltura Dynamic Video Player" frameborder="0" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" style="border: 0px; max-width: 100%; max-height: 100%; width: 100%; height: 100%;"></iframe></div>                    </div>
                    <div class="col-sm-12 block-content" data-block-identifier="block-#" >
                        <div class="clearfix hr-10" data-block-identifier="#"></div>
                        <h4 style="color: #ccf131;">Video Report</h4>
                        <h3 style="margin-top:5px;"><a href="#" style="color:#fefefe">Treatment Strategies and options in castration - resisant and advanced prostate cancer</a></h3>
                        <a href="#" style="color:#fefefe">Audrey Nailor and Ian Lewis</a>
                        <div class="clearfix hr-20" data-block-identifier="#"></div>
                    </div>
                    <div class="clearfix hr-20" data-block-identifier="#"></div>
                </div>
            </div>
            <div class="clearfix hr-20" data-block-identifier="#"></div>
            <div class="row">
                <div class="col-sm-d12 block-content" data-block-identifier="block-#" style="background-color:#296aa4">
                    <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" style="width:100%;">
                    <div class="col-sm-12 block-content" data-block-identifier="block-#" >
                        <div class="clearfix hr-5" data-block-identifier="#"></div>
                        <h4 style="color: #ccf131;">Case Report</h4>
                        <h3 style="margin-top:5px;"><a href="#" style="color:#fefefe">Utility of endomerial sampling prior to risk-reducing hysterectomy in a patient with Lynch syndrome</a></h3>
                        <a href="#" style="color:#fefefe">Audrey Nailor and Ian Lewis</a>
                        <div class="clearfix hr-20" data-block-identifier="#"></div>
                    </div>
                    <div class="col-sm-6 block-content" data-block-identifier="block-#" >
                        <div class="clearfix hr-5" data-block-identifier="#"></div>
                        <h6 style="color: #ccf131;">Published: 12/07/2016</h6>
                        <h6 style="color: #ccf131;">DOI</h6>
                    </div>
                    <div class="col-sm-6 block-content text-right" data-block-identifier="block-#" >
                        <div class="clearfix hr-5" data-block-identifier="#"></div>
                        <h6 style="color: #ccf131;"><a href="#" style="color: #ccf131;">Read More</a></h6>
                    </div>
                    <div class="clearfix hr-20" data-block-identifier="#"></div>
                </div>
            </div>
            <div class="clearfix hr-20" data-block-identifier="#"></div>
            <div class="row">
                <div class="col-sm-12 block-content" data-block-identifier="block-#" style="background-color:#709dc7">
                    <div class="row">
                        <div class="col-sm-4 block-content" data-block-identifier="block-#" style="background-color:#709dc7">
                            <img src="/assets/img/thumb-005.png" alt="" class="img-responsive">
                        </div>
                        <div class="col-sm-8 block-content" data-block-identifier="block-#" style="background-color:#709dc7">
                            <h6 style="color: #ccf131;">Conference Report</h6>
                            <p><a href="/conference/report/123">Orlando Magic: report from the 57th meeting of the American Society of Haematology, 5-7 December 2015, Orlando, USA</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="clearfix hr-20" data-block-identifier="#"></div>
                <div class="col-sm-12 block-content" data-block-identifier="block-#" style="background-color:#709dc7">
                    <div class="row">
                        <div class="col-sm-4 block-content" data-block-identifier="block-#" style="background-color:#709dc7">
                            <img src="/assets/img/thumb-004.png" alt="" class="img-responsive">
                        </div>
                        <div class="col-sm-8 block-content" data-block-identifier="block-#" style="background-color:#709dc7">
                            <h6 style="color: #ccf131;">Conference Report</h6>
                            <p><a href="/conference/report/123">Orlando Magic: report from the 57th meeting of the American Society of Haematology, 5-7 December 2015, Orlando, USA</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="clearfix hr-20" data-block-identifier="#"></div>
                <div class="col-sm-12 block-content" data-block-identifier="block-#" style="background-color:#709dc7">
                    <div class="row">
                        <div class="col-sm-4 block-content" data-block-identifier="block-#" style="background-color:#709dc7">
                            <img src="/assets/img/thumb-006.png" alt="" class="img-responsive">
                        </div>
                        <div class="col-sm-8 block-content" data-block-identifier="block-#" style="background-color:#709dc7">
                            <h6 style="color: #ccf131;">Conference Report</h6>
                            <p><a href="/conference/report/123">Orlando Magic: report from the 57th meeting of the American Society of Haematology, 5-7 December 2015, Orlando, USA</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="clearfix hr-20" data-block-identifier="#"></div>
</div>