<div class="container slide-home" data-area-identifier="area-004">
    <div class="row">
        <div class="col-md-4">
            <div data-block-identifier="block-005">
                <div id="carousel-home-narrow" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <div class="embed-responsive embed-responsive-16by9">
                                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/u7K72X4eo_s" frameborder="0" allowfullscreen></iframe>
                            </div>
                            <div>
                                <ul style="background-color:#212121;color:#fefefe">
                                    <li style="list-style-type: none;display:inline-block;width: 50%;">
                                        <label>Published:</label>
                                        <span>13.11.15</span>
                                    </li>
                                    <li style="list-style-type: none;float:left;width: 50%;">
                                        <label>Views:</label>
                                        <span>245</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="carousel-narrow-caption">
                                <div data-block-identifier="block-#">
                                    <h4>Video Report:</h4>
                                    <p>Treatment strategies and options in castration - resistant and advanced prostate cancer</p>
                                    <p>Audrey Mailor and Ian Lewis</p>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="embed-responsive embed-responsive-16by9">
                                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/u7K72X4eo_s" frameborder="0" allowfullscreen></iframe>
                            </div>
                            <div>
                                <ul style="background-color:#212121;color:#fefefe">
                                    <li style="list-style-type: none;display:inline-block;width: 50%;">
                                        <label>Published:</label>
                                        <span>13.11.15</span>
                                    </li>
                                    <li style="list-style-type: none;float:left;width: 50%;">
                                        <label>Views:</label>
                                        <span>245</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="carousel-narrow-caption">
                                <div data-block-identifier="block-#">
                                    <h4>Video Report:</h4>
                                    <p>Treatment strategies and options in castration - resistant and advanced prostate cancer</p>
                                    <p>Audrey Mailor and Ian Lewis</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div id="carousel-home-wide" class="carousel slide pause" data-ride="carousel">
                <script>$('#carousel-home-wide').carousel({
                interval: 200000000
                })</script>
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#carousel-home-wide" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-home-wide" data-slide-to="1"></li>
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Research:</h5>
                                            <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix hr-20" data-block-identifier="block-#"></div>
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-007.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Case Report:</h5>
                                            <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Research:</h5>
                                            <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix hr-20" data-block-identifier="block-#"></div>
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-007.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Case Report:</h5>
                                            <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Research:</h5>
                                            <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
                                        </div>
                                    </div>
                                    <div class="clearfix hr-5" data-block-identifier="block-#"></div>
                                </div>
                                <div class="clearfix hr-20" data-block-identifier="block-#"></div>
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-007.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Case Report:</h5>
                                            <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Research:</h5>
                                            <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix hr-20" data-block-identifier="block-#"></div>
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-007.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Case Report:</h5>
                                            <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Research:</h5>
                                            <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix hr-20" data-block-identifier="block-#"></div>
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-007.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Case Report:</h5>
                                            <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-008.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Research:</h5>
                                            <p class="block-text">Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper.</p>
                                        </div>
                                    </div>
                                    <div class="clearfix hr-5" data-block-identifier="block-#"></div>
                                </div>
                                <div class="clearfix hr-20" data-block-identifier="block-#"></div>
                                <div class="carousel-item-wrapper">
                                    <div>
                                        <img src="/assets/img/thumb-007.png" alt="" class="img-responsive" />
                                        <div class="carousel-item-wrapper-text wide">
                                            <h5>Case Report:</h5>
                                            <p class="block-text">Utility of endometrial sampling rpior to risk-reducing hysteroctomy in a patient with Lynch syndrome.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Left and right controls -->
                <a class="left carousel-control" href="#carousel-home-wide" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-home-wide" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <div class="clearfix hr-20" data-block-identifier="#"></div>
</div>
<?php echo $this->partial('content/area', array(
    'area' => $area['video_editor_choice'],
));
?>
<div class="container" data-area-identifier="area-006">
    <div class="row">
        <div class="col-sm-12 block-header" data-block-identifier="block-#">
            <h2 data-content-identifier="content-#">Videos by Conference</h2>
        </div>
        <div class="clearfix hr-5" data-block-identifier="block-#"></div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3 data-content-identifier="content-#">Headline</h3>
                <div class="content">
                    <p>Cras vitae ultricies purus. Aliquam non erat congue, vulputate eros vitae, convallis risus. Curabitur commodo venenatis semper. Nunc felis libero, tincidunt quis quam eu, faucibus finibus purus. Ut luctus porttitor lorem non aliquet.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 block-item wide" data-block-identifier="block-#">
            <div class="block-content-item-wrapper">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-0 wrapper-inner" data-block-identifier="block-#">
                        <h3 data-content-identifier="content-#">A longer headline</h3>
                        <p data-content-identifier="content-#" class="block-text">Praesent consectetur rutrum erat. Praesent dictum facilisis nibh at venenatis. Cras nec ante feugiat, lacinia mi in, dictum nulla. Nam congue pharetra justo eget interdum. Pellentesque aliquet, dolor at tempor rhoncus, libero orci pellentesque magna, sed rutrum massa lectus eget metus. Ut venenatis vulputate leo in accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque felis a odio sodales porttitor.</p>
                    </div>
                    <div class="col-sm-6" data-block-identifier="block-#">
                        <img data-content-identifier="content-#" src="/assets/img/img-010.png" alt="" class="img-responsive" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 block-item" data-block-identifier="block-#">
            <div class="block-content-item-wrapper wrapper-inner">
                <h3 data-content-identifier="content-#">Headline with video</h3>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/u7K72X4eo_s" frameborder="0" allowfullscreen></iframe>
                </div>
                <div>
                    <p>Ut luctus porttitor lorem non aliquet. Donec in turpis ac tortor pharetra suscipit. Sed varius risus mattis, convallis urna id, facilisis nunc.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="jumbotron" data-area-identifier="area-007">
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1" data-block-identifier="block-#">
                <img src="/assets/img/img-011.png" alt="" class="img-responsive" />
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12" data-block-identifier="block-#" style="background-color:#fff">
                <h2>e-learning for oncology professionals</h2>
                <div class="col-sm-3">
                    <img src="/assets/img/img-012.png" alt="" class="img-responsive" />
                </div>
                <div class="col-sm-9">
                    <p>ecancer provides e-learning courses for fee to the oncology community.</p>
                    <p>Our resources cover a variety of topics and have been developed in partnership with leading organisations and individuals. Oue e-larning is impactful and focuses on the end goal of improving patient care and outcomes.</p>
                    <p>Our resources are completely free of charge; all we ask is that you register for the ecancer club so that we are able to record our learning.</p>
                    <div class="clearfix hr-20"></div>
                    <button type="button" class="btn btn-success pull-right">Success</button>
                </div>
            </div>
        </div>
    </div>
</div>