<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.0.6/css/all.css')
    ->prependStylesheet('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css')
    ->appendStylesheet('/assets/css/theme-art13-1.css')
    ->appendStylesheet('/assets/css/bootstrap-multiselect.css')
;
$this->inlineScript()
    ->prependFile('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.3.1.slim.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js')
    ->appendFile('/assets/js/bootstrap-multiselect.js')
;

if($this->hasIdentity()):

    $this->inlineScript()
        ->appendFile('/assets/js/spa-editor.js')
        ->appendFile('/assets/js/secalith-zf-core.js')
        ->appendFile('/assets/js/secalith-zf-form.js')
        ->appendFile('/assets/js/spa-form.js')
        ->appendFile('/assets/js/spa-init.js')
    ;

endif;

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <meta property="og:image" content="http://art13/assets/img/1113.png"/>
    <meta property="og:image:secure_url" content="https://art13.eu/assets/img/1113.png" />

    <link rel="shortcut icon" href="https://framework.zend.com/ico/favicon.ico" />
    <?=$this->headTitle('11/13')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <style>
        body { padding-top: 70px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
    </style>
</head>
<body class="app app-theme-art13 <?=(isset($bodyClass))?$bodyClass:null;?>">

<div id="fb-root"></div>

    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v3.1&appId=2199972683623007&autoLogAppEvents=1';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <script>window.twttr = (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
            t = window.twttr || {};
        if (d.getElementById(id)) return t;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);

        t._e = [];
        t.ready = function(f) {
            t._e.push(f);
        };

        return t;
    }(document, "script", "twitter-wjs"));
</script>

    <header class="app-header">
        <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="<?=$this->url('home')?>">
                        <img src="/assets/img/1113.png" alt="art13.eu" height="28" />
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="">
                            <a href="<?=$this->url('home')?>" class="nav-link"><?=$this->translate("Homepage");?></a>
                        </li>
                        <?php if( ! $this->hasIdentity()):?>

                        <?php else: ?>
                            <li class="nav-item">
                                <a href="<?=$this->url('manager.event.list')?>" class="nav-link"><?=$this->translate("Events");?></a>
                            </li>
                        <?php endif;?>
                    </ul>
                    <ul class="navbar-nav navbar-right align-middle">
                            <li class="nav-item mr-3 mt-1 align-top">
                                <a class="twitter-share-button"
                                   href="https://twitter.com/intent/tweet?text=#Stopacta2 #deleteart13 #antyart13 #saveyourinternet"
                                   data-size="default">
                                    Tweet</a>
                            </li>
                            <li class="nav-item mr-3 mt-0">
                                <div class="fb-share-button align-middle" data-href="https://art13.eu" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fart13.eu%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Udostępnij</a></div>
                            </li>
                        <?php if( ! $this->hasIdentity()):?>
                            <li class="nav-item mr-2">
                                <a href="<?=$this->url('manager.register')?>" class="nav-link btn btn-sm btn-secondary text-light"><?=$this->translate('Sign Up');?></a>
                            </li>
                            <li class="nav-item">
                                <a href="<?=$this->url('spa.auth')?>" class="nav-link btn btn-sm btn-secondary text-light"><?=$this->translate('Sign In');?></a>
                            </li>
                        <?php else: ?>
                            <li class="nav-item">
                                <a href="<?=$this->url('spa.auth.logout')?>" class="nav-link btn btn-sm btn-secondary text-light"><?=$this->translate("Sign Out");?></a>
                            </li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <div class="row">
                <div class="col-12 m-auto" role="main">
                    <?=($this->content);?>
                    <?php
if (isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
            // break up string into pieces (languages and q factors)
            preg_match_all(
                '/([a-z]{1,8}(-[a-z]{1,8})?)\s*(;\s*q\s*=\s*(1|0\.[0-9]+))?/i',
                $_SERVER['HTTP_ACCEPT_LANGUAGE'],
                $lang_parse
            );

            if (count($lang_parse[1])) {
                // create a list like 'en' => 0.8
                $langs = array_combine($lang_parse[1], $lang_parse[4]);

                // set default to 1 for any without q factor
                foreach ($langs as $lang => $val) {
                    if ($val === '') {
                        $langs[$lang] = 1;
                    }
                }
                // sort list based on value
                arsort($langs, SORT_NUMERIC);
            }
        }
        //extract most important (first)
        reset($langs);
        $lang = key($langs);

        //if complex language simplify it
        if (stristr($lang, '-')) {
            list($lang) = explode('-', $lang);
        }

        echo $lang . "_" . $lang;

?>
                    ?>
                </div>
            </div>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container"></div>
    </footer>

    <?=$this->inlineScript()?>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-121422820-1"></script>
    <script>

        var counters = $('[id^=time_counter-]');
        for(var i=0;i<counters.length;i++) {
            var date = counters.eq(i).attr('data-countdown');
            counters.eq(i).flipcountdown({
                beforeDateTime: date,
                showHour:true,
                showMinute:false,
                showSecond:false,
                size: 'sm'
            });
        }

        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-121422820-1');
    </script>

</body>
</html>
