<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.0.6/css/all.css')
    ->prependStylesheet('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css')
    ->appendStylesheet('/assets/css/theme-art13-1.css')
    ->appendStylesheet('/assets/css/bootstrap-multiselect.css')
    ->appendStylesheet('/assets/css/bootstrap.switch.css')
    ->appendStylesheet('/assets/js/flipcountdown/jquery.flipcountdown.css')
;
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.3.1.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js')
    ->appendFile('/assets/js/bootstrap-multiselect.js')
    ->appendFile('/assets/js/flipcountdown/jquery.flipcountdown.js')
    ->appendFile('/assets/js/spa-init-public.js')
;

if($this->hasIdentity()):

    $this->inlineScript()
        ->appendFile('/assets/js/spa-ajax.js')
        ->appendFile('/assets/js/spa-editor.js')
        ->appendFile('/assets/js/secalith-zf-core.js')
        ->appendFile('/assets/js/secalith-zf-form.js')
        ->appendFile('/assets/js/spa-form.js')
        ->appendFile('/assets/js/spa-init.js')
    ;

    $this->headLink()
        ->appendStylesheet('/assets/css/spa-editor.css')
    ;

endif;

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <meta property="og:image" content="http://art13.eu/assets/img/1113.png"/>
    <meta property="og:image:secure_url" content="https://art13.eu/assets/img/1113.png" />

    <?=$this->headTitle('Art. 11')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>

    <link rel="apple-touch-icon" sizes="180x180" href="https://art13.eu/assets/favicons/1113/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://art13.eu/assets/favicons/1113/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://art13.eu/assets/favicons/1113/favicon-16x16.png">
    <link rel="manifest" href="https://art13.eu/assets/favicons/1113/site.webmanifest">
    <link rel="mask-icon" href="https://art13.eu/assets/favicons/1113/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="https://art13.eu/assets/favicons/1113/favicon.ico">
    <meta name="msapplication-TileColor" content="#efefef">
    <meta name="msapplication-config" content="https://art13.eu/assets/favicons/1113/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <link rel="shortcut icon" href="https://art13.eu/assets/favicons/1113/favicon-32x32.png" />

</head>

<body class="app app-theme-art13 <?=(isset($bodyClass))?$bodyClass:null;?>">

<div id="fb-root"></div>

    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v3.1&appId=2199972683623007&autoLogAppEvents=1';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <script>window.twttr = (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
            t = window.twttr || {};
        if (d.getElementById(id)) return t;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);

        t._e = [];
        t.ready = function(f) {
            t._e.push(f);
        };

        return t;
    }(document, "script", "twitter-wjs"));
</script>

    <header class="app-header">

        <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top" role="navigation">
            <div class="container">

                <div class="navbar-header w-100 d-flex justify-content-between">
                    <a id="site-logo" class="navbar-brand d-inline-block mt-1 float-left" href="/">
                        <img src="https://art13.eu/assets/img/1113.png" alt="art13.eu" height="28" />
                    </a>

                    <ul class="navbar-nav d-none d-md-inline-block">
                        <li class="nav-item d-none d-lg-inline-block mt-2 p-0">
                            <a href="<?=$this->url('home')?>" class="nav-link scroll-trigger"><?=$this->translate("Homepage");?></a>
                        </li>
                        <li class="nav-item d-inline-block mt-2 p-0">
                            <a href="<?=$this->url('home')?>#events" class="nav-link scroll-trigger"><?=$this->translate("Events");?></a>
                        </li>
                        <li class="nav-item d-inline-block mt-2 p-0">
                            <a href="https://peticio.art13.eu" class="nav-link scroll-trigger"><?=$this->translate("Petition");?></a>
                        </li>
                        <li class="nav-item d-inline-block mt-2 p-0">
                            <a href="<?=$this->url('home')?>#information" class="nav-link scroll-trigger"><?=$this->translate("Information");?></a>
                        </li>
                    </ul>

                    <div class="d-inline-block m-0 mt-2 p-0">
                        <span class="float-md-right mt-1 mr-0" id="time_counter-first" data-countdown="2018/08/26 18:00"></span>
                    </div>

                    <button type="button" class="navbar-toggler float-right " data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <?php if( $this->hasIdentity()):?>
                    <ul class="navbar-nav d-none d-md-inline-block">
                        <li class="nav-item ml-3">
                            <div class="btn-group">
                                <button type="button" class="btn btn-info"><?=$this->translate("Manage");?></button>
                                <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="<?=$this->url('manager.event.list')?>"><?=$this->translate("Events");?></a>
                                    <a class="dropdown-item" href="<?=$this->url('manager.petition.list')?>"><?=$this->translate("Petitions");?></a>
                                    <a class="dropdown-item" href="<?=$this->url('manager.article.list')?>"><?=$this->translate("Articles");?></a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#"><?=$this->translate("Resources");?></a>
                                    <a class="dropdown-item" href="#"><?=$this->translate("Page SEO");?></a>
                                    <a class="dropdown-item" href="#"><?=$this->translate("Settings");?></a>
                                    <a class="dropdown-item" href="#"><?=$this->translate("Your Account");?></a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item d-inline-block mt-2 p-0">
                            <a href="<?=$this->url('spa.auth.logout')?>" class="btn btn-secondary d-inline-block"><?=$this->translate("Sign Out");?></a>
                        </li>
                    </ul>
                    <ul class="navbar-nav d-none d-md-inline-block">
                        <li class="nav-item ml-3">
                            <div class="btn-group">
                                <button type="button" class="btn btn-info"><?=$this->translate("Edit");?></button>
                                <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item menu-item menu-item-area" href="#" data-item-type="area"><?=_("Area");?></a>
                                    <a class="dropdown-item menu-item menu-item-block" href="#" data-item-type="block"><?=_("Block");?></a>
                                    <a class="dropdown-item menu-item menu-item-content" href="#" data-item-type="content"><?=_("Content");?></a>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <?php endif;?>

                </div>

                <div class="collapse navbar-collapse" id="navbarCollapse">

                    <ul class="navbar-nav mr-auto mt-2 d-md-none border-top">
                        <li class="nav-item">
                            <a href="<?=$this->url('home')?>#events" class="nav-link scroll-trigger"><?=$this->translate("Events");?></a>
                        </li>

                        <li class="nav-item">
                            <a href="#petition" class="nav-link scroll-trigger"><?=$this->translate("Petition");?></a>
                        </li>

                        <li class="nav-item">
                            <a href="<?=$this->url('home')?>#information" class="nav-link scroll-trigger"><?=$this->translate("Information");?></a>
                        </li>
                        <li class="nav-item d-block d-md-none border-top">
                            <a href="<?=$this->url('spa.auth.logout')?>" class="nav-link"><?=$this->translate("Sign Out");?></a>
                        </li>
                    </ul>

                </div>

            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <div class="row">
                <div class="col-12 m-auto" role="main">
                    <?=($this->content);?>
                </div>
            </div>
        </main>
    </div>


    <div id="form-fixed-save-observer" class="hidden navbar navbar-expand-md navbar-light  fixed-bottom" style="position:fixed;bottom:0px;background: #000000;">
        <div class="container">
            <div class="row">
                <div class="col-12 py-3">
                    <ul class="d-flex justify-content-between list-unstyled text-small mb-0">
                        <li class="d-inline mr-4 text-light"><?=$this->translate("Content has changed. Do you want to save the progress?");?></li>
                        <li class="d-inline mr-4"><a class="btn btn-danger" href="#"><?=$this->translate('Discard changes');?></a></li>
                        <li class="d-inline mr-4"><a class="btn btn-success" href="#"><?=$this->translate('Save progress');?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <footer class="app-footer footer">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <ul class="d-flex justify-content-between list-unstyled text-small mb-0">
                        <li class="d-inline mr-4"><a href="<?=$this->url('home')?>" class="text-muted"><?=$this->translate("Homepage");?></a></li>
                        <li class="d-inline mr-4"><a class="text-muted" href="#"><?=$this->translate('About');?></a></li>
                        <li class="d-inline mr-4"><a class="text-muted" href="/privacy-policy"><?=$this->translate('Privacy');?></a></li>
                        <li class="d-inline mr-4"><a class="text-muted" href="#"><?=$this->translate('T&C');?></a></li>
                        <?php if( $this->hasIdentity()):?>
                            <li class="d-inline mr-4"><a class="text-muted" href="<?=$this->url('spa.auth.logout')?>"><?=$this->translate("Sign Out");?></a></li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <div id="content-update-mode-switch" data-default="inline">
        <span><?=_("Inline Edit");?></span>
        <span class="switch p-2 pl-1">
            <input type="checkbox" class="switch" checked="checked" id="switch-id" />
            <label for="switch-id">&nbsp;</label>
        </span>
    </div>
    <div id="content-update-autosave-switch" data-default="inline">
        <span><?=_("Autosave");?></span>
        <span class="switch p-2 pl-1">
            <input type="checkbox" class="switch" id="switch-autosave" />
            <label for="switch-autosave">&nbsp;</label>
        </span>
    </div>

    <div class="scroll-top-trigger-wrapper scroll-trigger" data-scroll-target="body">
        <img src="/assets/icons/iconic-1.1.10/png/arrow-circle-top-6x.png" alt="Top" />
    </div>

    <?=$this->inlineScript()?>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-121422820-1"></script>
    <script>

        var counters = $('[data-countdown]');
        for(var i=0;i<counters.length;i++) {
            var date = counters.eq(i).attr('data-countdown');
            counters.eq(i).flipcountdown({
                beforeDateTime: date,
                showHour:true,
                showMinute:false,
                showSecond:false,
                size: 'sm'
            });
        }

        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-121422820-1');
    </script>

    <script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>

</body>
</html>
