<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.0.6/css/all.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css')
    ->appendStylesheet('/assets/css/theme-manager.css')
    ->appendStylesheet('/assets/css/bootstrap-multiselect.css')
;
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.3.1.min.js')
    ->prependFile('/assets/js/popper.min.js')
    ->appendFile('/assets/js/bootstrap-multiselect.js')
;

if($this->hasIdentity()):

    $this->inlineScript()
        ->appendFile('/assets/js/spa-editor.js')
        ->appendFile('/assets/js/secalith-zf-core.js')
        ->appendFile('/assets/js/secalith-zf-form.js')
        ->appendFile('/assets/js/spa-form.js')
        ->appendFile('/assets/js/spa-init.js')
    ;

endif;

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="https://framework.zend.com/ico/favicon.ico" />
    <?=$this->headTitle('11/13')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
</head>
<body class="app app-theme-manager <?=(isset($bodyClass))?$bodyClass:null;?>">
    <header class="app-header">
        <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="https://art13.eu">
                        <img src="/assets/img/1113.png" alt="art11.eu" height="28" />
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="/" class="nav-link"><?=$this->translate("Homepage");?></a>
                        </li>
                        <?php if( ! $this->hasIdentity()):?>

                        <?php else: ?>
                            <li class="nav-item float-right">
                                <a href="<?=$this->url('manager.event.list')?>" class="nav-link"><?=$this->translate('Events');?></a>
                            </li>
                            <li class="nav-item">
                                <a href="<?=$this->url('manager.petition.list')?>" class="nav-link"><?=$this->translate("Petitions");?></a>
                            </li>
                            <li class="nav-item">
                                <a href="<?=$this->url('manager.article.list')?>" class="nav-link"><?=$this->translate("Articles");?></a>
                            </li>
                        <?php endif;?>
                    </ul>
                    <ul class="navbar-nav navbar-right align-right">
                        <?php if( $this->hasIdentity()):?>
                            <li class="nav-item ml-3">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-info"><?=$this->translate("Manage");?></button>
                                    <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="sr-only">Toggle Dropdown</span>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="<?=$this->url('manager.event.list')?>"><?=$this->translate("Events");?></a>
                                        <a class="dropdown-item" href="<?=$this->url('manager.petition.list')?>"><?=$this->translate("Petitions");?></a>
                                        <a class="dropdown-item" href="<?=$this->url('manager.article.list')?>"><?=$this->translate("Articles");?></a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#"><?=$this->translate("Resources");?></a>
                                        <a class="dropdown-item" href="#"><?=$this->translate("Page SEO");?></a>
                                        <a class="dropdown-item" href="#"><?=$this->translate("Settings");?></a>
                                        <a class="dropdown-item" href="#"><?=$this->translate("Your Account");?></a>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item ml-3">
                                <a href="<?=$this->url('spa.auth.logout')?>" class="nav-link btn btn-sm btn-secondary text-light"><?=$this->translate("Sign Out");?></a>
                            </li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container-fluid">
            <div class="row">
                <div class="col-12 m-auto px-4" role="main">
                    <noscript>
                        <div class="alert alert-danger">
                            <p><?=$this->translate('**Warning!** The JavaScript support must be enabled.');?></p>
                        </div>
                    </noscript>
                    <?=($this->content);?>
                </div>
            </div>
        </main>
    </div>

<footer class="app-footer footer">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <ul class="d-flex justify-content-between list-unstyled text-small mb-0">
                    <li class="d-inline mr-4"><a class="text-muted" href="#"><a href="/" class="text-muted"><?=$this->translate("Homepage");?></a></a></li>
                    <li class="d-inline mr-4"><a class="text-muted" href="#"><?=$this->translate('About');?></a></li>
                    <li class="d-inline mr-4"><a class="text-muted" href="/privacy-policy"><?=$this->translate('Privacy Policy');?></a></li>
                    <li class="d-inline mr-4"><a class="text-muted" href="#"><?=$this->translate('Terms and Conditions');?></a></li>
                    <li class="d-inline mr-4"><a class="text-muted" href="#"><?=$this->translate('List Petitions');?></a></li>
                    <?php if( ! $this->hasIdentity()):?>
                        <li class="d-inline mr-4"><a class="text-muted" href="<?=$this->url('manager.register')?>"><?=$this->translate('Sign Up');?></a></li>
                        <li class="d-inline mr-4"><a class="text-muted" href="<?=$this->url('spa.auth')?>"><?=$this->translate('Sign In');?></a></li>
                    <?php else: ?>
                        <li class="d-inline mr-4"><a class="text-muted" href="<?=$this->url('spa.auth.logout')?>"><?=$this->translate("Sign Out");?></a></li>
                    <?php endif;?>
            </div>
        </div>
    </div>
</footer>

    <?=$this->inlineScript()?>

    <script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('.bt-multiselect').multiselect();
        });
    </script>

</body>
</html>
