<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.0.6/css/all.css')
    ->prependStylesheet('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css')
    ->appendStylesheet('/assets/css/theme-peticio-1.css')
    ->appendStylesheet('/assets/css/bootstrap-multiselect.css')
    ->appendStylesheet('/assets/js/flipcountdown/jquery.flipcountdown.css')
;
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.3.1.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js')
    ->appendFile('/assets/js/bootstrap-multiselect.js')
    ->appendFile('/assets/js/flipcountdown/jquery.flipcountdown.js')
;

if($this->hasIdentity()):

    $this->inlineScript()
        ->appendFile('/assets/js/spa-editor.js')
        ->appendFile('/assets/js/secalith-zf-core.js')
        ->appendFile('/assets/js/secalith-zf-form.js')
        ->appendFile('/assets/js/spa-form.js')
        ->appendFile('/assets/js/spa-init.js')
    ;

endif;

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <meta property="og:image" content="http://art13.eu/assets/img/1113.png"/>
    <meta property="og:image:secure_url" content="https://art13.eu/assets/img/1113.png" />

    <link rel="apple-touch-icon" sizes="180x180" href="https://art13.eu/assets/favicons/1113/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://art13.eu/assets/favicons/1113/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://art13.eu/assets/favicons/1113/favicon-16x16.png">
    <link rel="manifest" href="https://art13.eu/assets/favicons/1113/site.webmanifest">
    <link rel="mask-icon" href="https://art13.eu/assets/favicons/1113/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="https://art13.eu/assets/favicons/1113/favicon.ico">
    <meta name="msapplication-TileColor" content="#efefef">
    <meta name="msapplication-config" content="https://art13.eu/assets/favicons/1113/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <link rel="shortcut icon" href="https://art13.eu/assets/favicons/1113/favicon-32x32.png" />
    <?=$this->headTitle('Art. 11')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
</head>

<body class="app app-theme-art13 <?=(isset($bodyClass))?$bodyClass:null;?>">

<div id="fb-root"></div>

    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v3.1&appId=2199972683623007&autoLogAppEvents=1';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <script>window.twttr = (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
            t = window.twttr || {};
        if (d.getElementById(id)) return t;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);

        t._e = [];
        t.ready = function(f) {
            t._e.push(f);
        };

        return t;
    }(document, "script", "twitter-wjs"));
</script>

    <header class="app-header">

        <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top" role="navigation">
            <div class="container">

                <div class="navbar-header w-100 d-flex justify-content-between">
                    
                    <a id="site-logo" class="navbar-brand d-inline-block mt-1 float-left" href="/">
                        <img src="https://art13.eu/assets/img/1113.png" alt="art13.eu" height="28" />
                    </a>

                    <div class="d-inline-block m-0 mt-2 p-0">
                        <span class="float-md-right mt-1 mr-0" id="time_counter-first" data-countdown="2018/08/26 18:00"></span>
                    </div>

                    <button type="button" class="navbar-toggler float-right " data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                </div>

                <div class="collapse navbar-collapse" id="navbarCollapse">

                    <ul class="navbar-nav mr-auto mt-2 d-md-none border-top">

                        <li class="nav-item">
                            <a href="https://peticio.art13.eu" class="nav-link scroll-trigger"><?=$this->translate("Petition");?></a>
                        </li>
                    </ul>

                </div>

            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <div class="row">
                <div class="col-12 m-auto" role="main">
                    <?=($this->content);?>
                </div>
            </div>
        </main>
    </div>

    <footer class="app-footer footer">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <ul class="d-flex justify-content-between list-unstyled text-small mb-0">
                        <li class="d-inline mr-4"><a class="text-muted" href="/privacy-policy"><?=$this->translate('Privacy Policy');?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <?=$this->inlineScript()?>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-121422820-2"></script>
    <script>

        var counters = $('[id^=time_counter-]');
        for(var i=0;i<counters.length;i++) {
            var date = counters.eq(i).attr('data-countdown');
            counters.eq(i).flipcountdown({
                beforeDateTime: date,
                showHour:true,
                showMinute:false,
                showSecond:false,
                size: 'sm'
            });
        }

        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-121422820-2');
    </script>

    <script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>

</body>
</html>
