<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.0.6/css/all.css')
    ->prependStylesheet('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css')
    ->appendStylesheet('/assets/css/theme-shrt-1.css')
    ->appendStylesheet('/assets/css/bootstrap-multiselect.css')
    ->appendStylesheet('/assets/js/flipcountdown/jquery.flipcountdown.css')
;
$this->inlineScript()

    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js')
    ->appendFile('/assets/js/bootstrap-multiselect.js')
    ->appendFile('/assets/js/flipcountdown/jquery.flipcountdown.js')
;

if($this->hasIdentity()):

    $this->inlineScript()
        ->appendFile('/assets/js/spa-editor.js')
        ->appendFile('/assets/js/secalith-zf-core.js')
        ->appendFile('/assets/js/secalith-zf-form.js')
        ->appendFile('/assets/js/spa-form.js')
        ->appendFile('/assets/js/spa-init.js')
    ;

endif;

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <meta property="og:image" content="http://shrt.ovh/assets/img/1113.png"/>
    <meta property="og:image:secure_url" content="https://shrt.ovh/assets/img/1113.png" />

    <link rel="shortcut icon" href="https://framework.zend.com/ico/favicon.ico" />
    <?=$this->headTitle('Shrt.ovh')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
</head>
<body class="app app-theme-shrt <?=(isset($bodyClass))?$bodyClass:null;?>">

<div id="fb-root"></div>

    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v3.1&appId=2199972683623007&autoLogAppEvents=1';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <script>window.twttr = (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
            t = window.twttr || {};
        if (d.getElementById(id)) return t;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);

        t._e = [];
        t.ready = function(f) {
            t._e.push(f);
        };

        return t;
    }(document, "script", "twitter-wjs"));
</script>

    <header class="app-header">
        <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="<?=$this->url('shrt.home')?>">
                        <img src="https://shrt.ovh/assets/img/1113.png" alt="shrt.ovh" height="28" />
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="<?=$this->url('shrt.home')?>" class="nav-link"><?=$this->translate("Shorten");?></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <div class="row">
                <div class="col-12 m-auto" role="main">
                    <?=($this->content);?>
                </div>
            </div>
        </main>
    </div>

    <footer class="app-footer footer">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <ul class="d-flex justify-content-between list-unstyled text-small mb-0">
                        <li class="d-inline mr-4"><a class="text-muted" href="#"><a href="<?=$this->url('shrt.home')?>" class="text-muted"><?=$this->translate("Homepage");?></a></a></li>
                        <li class="d-inline mr-4"><a class="text-muted" href="#"><?=$this->translate('About');?></a></li>
                        <li class="d-inline mr-4"><a class="text-muted" href="#"><?=$this->translate('Privacy Policy');?></a></li>
                        <li class="d-inline mr-4"><a class="text-muted" href="#"><?=$this->translate('Terms and Conditions');?></a></li>
                        <?php if( ! $this->hasIdentity()):?>
                            <li class="d-inline mr-4"><a class="text-muted" href="#"><?=$this->translate('Sign Up');?></a></li>
                            <li class="d-inline mr-4"><a class="text-muted" href="#"><?=$this->translate('Sign In');?></a></li>
                        <?php else: ?>
                            <li class="d-inline mr-4"><a class="text-muted" href="#"><?=$this->translate("Sign Out");?></a></li>
                        <?php endif;?>
                </div>
            </div>
        </div>
    </footer>

    <?=$this->inlineScript()?>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-121422820-1"></script>
    <script>

        var counters = $('[id^=time_counter-]');
        for(var i=0;i<counters.length;i++) {
            var date = counters.eq(i).attr('data-countdown');
            counters.eq(i).flipcountdown({
                beforeDateTime: date,
                showHour:true,
                showMinute:false,
                showSecond:false,
                size: 'sm'
            });
        }

        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-121422820-1');
    </script>

</body>
</html>
