<?php

$form->prepare();

//  fieldset_event
//  fieldset_event_details

?>

<?=$this->form()->openTag($form);?>

<?=$this->formElementErrors($form->get('application_id'));?>
<?=$this->formElementErrors($form->get('csrf'));?>

<div>
    <div class="container pt-2">

        <div class="row">
            <div class="col-12 col-md-10 py-2 px-0 text-justify">
                <p>On this page you will be able to register your event with us. We will need the most basic information about the dates, place or languages displayed on the website.</p>
            </div>
            <div class="col-12 col-md-2 py-2 px-0 text-right">
                <?=$this->formSubmit($form->get('submit'));?>
            </div>
        </div>

            <?=$this->formInput($form->get('form_create')->get('fieldset_article')->get('uid'));?>
            <?=$this->formInput($form->get('form_create')->get('fieldset_article')->get('application_uid'));?>
            <?=$this->formInput($form->get('form_create')->get('fieldset_article')->get('site_uid'));?>

            <?=$this->formElementErrors($form->get('form_create')->get('fieldset_article')->get('uid'));?>
            <?=$this->formElementErrors($form->get('form_create')->get('fieldset_article')->get('application_uid'));?>
            <?=$this->formElementErrors($form->get('form_create')->get('fieldset_article')->get('site_uid'));?>

        <div class="row">
            <div class="col-12 py-2 px-0">
                <h3 class="display-5"><?=$this->translate("Some basic information about your Article");?></h3>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_create')->get('fieldset_article')->get('name'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_create')->get('fieldset_article')->get('name'))))?'has-errors':'';?>">
                <?=$this->formInput($form->get('form_create')->get('fieldset_article')->get('name'));?>
                <?=$this->formElementErrors($form->get('form_create')->get('fieldset_article')->get('name'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('This name will be visible only by you and other registered users.');?></small>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_create')->get('fieldset_article')->get('country'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_create')->get('fieldset_article')->get('country'))))?'has-errors':'';?>">
                <?=$this->formSelect($form->get('form_create')->get('fieldset_article')->get('country'));?>
                <?=$this->formElementErrors($form->get('form_create')->get('fieldset_article')->get('country'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Tell us the country where your article is (will be) published.');?></small>
            </div>
        </div>

    </div>
</div>

<hr />

<div class="form-container <?=($form->getMessages())?'form-has-errors':null;?>">

    <h3 class="display-5"><?=$this->translate("Your Event details");?></h3>

    <div class="container pt-2">


        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_create')->get('fieldset_article')->get('article_group'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_create')->get('fieldset_article')->get('article_group'))))?'has-errors':'';?>">
                <?=$this->formSelect($form->get('form_create')->get('fieldset_article')->get('article_group'));?>
                <?=$this->formElementErrors($form->get('form_create')->get('fieldset_article')->get('article_group'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Is your Event as part of something bigger?');?></small>
            </div>
        </div>

    </div>

    <hr />

    <h3 class="display-5"><?=$this->translate("Your event external links");?></h3>

    <div class="container pt-2">
        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_create')->get('fieldset_article')->get('status'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_create')->get('fieldset_article')->get('status'))))?'has-errors':'';?>">
                <?=$this->formSelect($form->get('form_create')->get('fieldset_article')->get('status'));?>
                <?=$this->formElementErrors($form->get('form_create')->get('fieldset_article')->get('status'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Should you Article be visible in public?');?></small>
            </div>
        </div>

    </div>

    <hr />
    <div class="py-2 px-3 mb-2">
        <?=$this->formSubmit($form->get('submit'));?>
    </div>

    <div class="hidden">
        <?=$this->formElement($form->get('application_id'));?>
        <?=$this->formElement($form->get('csrf'));?>
    </div>

</div>

<?=$this->form()->closeTag();?>

