<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'single-page-application/update/update' => __DIR__ . '/view/single-page-application/update/update.phtml',
    'content/area'                          => __DIR__ . '/view/content/area.phtml',
);
