<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Common\Module'                                                         => __DIR__ . '/Module.php',
    'Common\DataSelector\Service\DataSelectorService'                       => __DIR__ . '/src/DataEntity/Service/DataSelectorService.php',
    'Common\DataSelector\Service\Factory\DataSelectorServiceFactory'        => __DIR__ . '/src/DataEntity/Service/Factory/DataSelectorServiceFactory.php',
    'Common\DataSelector\Controller\Delegator\DataSelectorDelegatorFactory' => __DIR__ . '/src/DataSelector/Controller/Delegator/DataSelectorDelegatorFactory.php',
    'Common\Settings\Service\Factory\TableServiceFactory'                   => __DIR__ . '/src/Settings/Service/Factory/TableServiceFactory.php',
    'Common\Settings\Service\Factory\TableGatewayFactory'                   => __DIR__ . '/src/Settings/Service/Factory/TableGatewayFactory.php',
    'Common\Route\Service\Factory\RouteServiceFactory'                      => __DIR__ . '/src/Route/Service/Factory/RouteServiceFactory.php',
    'Common\Route\Service\RouteService'                                     => __DIR__ . '/src/Route/Service/RouteService.php',
    'Common\Settings\Controller\Delegator\SettingsDelegatorFactory'         => __DIR__ . '/src/Settings/Controller/Delegator/SettingsDelegatorFactory.php',
    'Common\Settings\Model\Model'                                           => __DIR__ . '/src/Settings/Model/Model.php',
    'Common\Settings\Model\Table'                                           => __DIR__ . '/src/Settings/Model/Table.php',
    'Common\FormData\Controller\Delegator\FormDataDelegatorFactory'         => __DIR__ . '/src/FormData/Controller/Delegator/FormDataDelegatorFactory.php',
    'Common\DataSelector\Controller\Delegator\DataEntityDelegatorFactory'   => __DIR__ . '/src/DataEntity/Controller/Delegator/DataEntityDelegatorFactory.php',
    'Common\DataMap\Service\Factory\DataMapServiceFactory'                  => __DIR__ . '/src/DataMap/Service/Factory/DataMapServiceFactory.php',
    'Common\DataMap\Service\DataMapService'                                 => __DIR__ . '/src/DataMap/Service/DataMapService.php',
    'Common\Controller\Delegator\Delegator'                                 => __DIR__ . '/src/Common/Controller/Delegator/Delegator.php',
    'Common\Controller\CommonController'                                    => __DIR__ . '/src/Common/Controller/CommonController.php',
    'Common\Template\Controller\Delegator\DelegatorFactory'                 => __DIR__ . '/src/Template/Controller/Delegator/DelegatorFactory.php',
    'Common\Form\Controller\Delegator\FormDelegatorFactory'                 => __DIR__ . '/src/Form/Controller/Delegator/FormDelegatorFactory.php',
);
