<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="well">
            <?php

            $formName = sprintf("%s_login",$module);

            echo $this->partial('_form_login.phtml', array(
                'form' => $form[$formName]['form'],
                'formName' => $formName,
                'module' => $module,
                'submodule' => $submodule,
                'keyword' => $keyword,
                'formType' => 'login',
                'formView' => $formView,
                'moduleFormLocation'=>$moduleFormLocation,
                'matchedRouteSuffix' => $matchedRouteSuffix,
                'matchedModuleDataNamespace' => $matchedModuleDataNamespace,
            ));?>
        </div>
        <div class="clearfix"></div>
    </div>
</div>