<?php

$form->prepare();

?>

<?=$this->form()->openTag($form);?>

<?=$this->formElementErrors($form->get('application_id'));?>
<?=$this->formElementErrors($form->get('csrf'));?>

<div>
    <div class="container-fluid pt-2">

        <div class="row">
            <div class="col-12 col-md-10 py-2 text-justify">
                <p>On this page you will be able to register your event with us. We will need the most basic information about the dates, place or languages displayed on the website.</p>
            </div>
            <div class="col-12 col-md-2 py-2 text-right">
                <?=$this->formSubmit($form->get('submit'));?>
            </div>
            <div class="col-12 py-2">
                <hr />
            </div>
        </div>

            <?=$this->formInput($form->get('form_update')->get('fieldset_event')->get('uid'));?>
            <?=$this->formInput($form->get('form_update')->get('fieldset_event')->get('application_uid'));?>
            <?=$this->formInput($form->get('form_update')->get('fieldset_event')->get('site_uid'));?>
            <?=$this->formInput($form->get('form_update')->get('fieldset_event_details')->get('event_uid'));?>
            <?=$this->formInput($form->get('form_update')->get('fieldset_event_details')->get('uid'));?>

            <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event')->get('uid'));?>
            <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event')->get('application_uid'));?>
            <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event')->get('site_uid'));?>
            <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('event_uid'));?>
            <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('uid'));?>

        <div class="row">
            <div class="col-12 py-2">
                <h3 class="display-5"><?=$this->translate("Some basic information about your Event");?></h3>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event')->get('name'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event')->get('name'))))?'has-errors':'';?>">
                <?=$this->formInput($form->get('form_update')->get('fieldset_event')->get('name'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event')->get('name'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('This name will be visible only by you and other registered users.');?></small>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event')->get('country'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event')->get('country'))))?'has-errors':'';?>">
                <?=$this->formSelect($form->get('form_update')->get('fieldset_event')->get('country'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event')->get('country'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Tell us the country where your event will be held.');?></small>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event_details')->get('name_global'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('name_global'))))?'has-errors':'';?>">
                <?=$this->formInput($form->get('form_update')->get('fieldset_event_details')->get('name_global'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('name_global'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('This name will be present to users from other countries than yours.');?></small>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event_details')->get('name'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('name'))))?'has-errors':'';?>">
                <?=$this->formInput($form->get('form_update')->get('fieldset_event_details')->get('name'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('name'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('This name will be visible for users from your country.');?></small>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event_details')->get('date_start'));?>
            </div>
            <div class="col-12 col-md-3 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('date_start'))))?'has-errors':'';?>">
                <?=$this->formDateTime($form->get('form_update')->get('fieldset_event_details')->get('date_start'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('date_start'));?>
            </div>

            <div class="col-12 col-md-2 py-2 px-0 pl-4 pr-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('timezone'))))?'has-errors':'';?>">
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('timezone'));?>
                <?=$this->formSelect($form->get('form_update')->get('fieldset_event_details')->get('timezone'));?>
            </div>

            <div class="col-12 col-md-5 py-2 px-0 pl-md-5 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('date_finish'))))?'has-errors':'';?>">
                <div class="d-block mt-1">
                    <?=$this->formCheckbox($form->get('form_update')->get('fieldset_event_details')->get('date_finish_display'));?>
                    <?=$this->formLabel($form->get('form_update')->get('fieldset_event_details')->get('date_finish_display'));?>
                    <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('date_finish_display'));?>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event_details')->get('date_finish'));?>
            </div>
            <div class="col-12 col-md-3 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('date_finish'))))?'has-errors':'';?>">
                <?=$this->formDateTime($form->get('form_update')->get('fieldset_event_details')->get('date_finish'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('date_finish'));?>
            </div>
        </div>

    </div>
</div>

<hr />

<div class="form-container <?=($form->getMessages())?'form-has-errors':null;?>">

    <h3 class="display-5"><?=$this->translate("Your Event details");?></h3>

    <div class="container-fluid pt-2">

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event_details')->get('language'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('language'))))?'has-errors':'';?>">
                <?=$this->formSelect($form->get('form_update')->get('fieldset_event_details')->get('language'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('language'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Which language will be primary at your Event?');?></small>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event_details')->get('city_global'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('city_global'))))?'has-errors':'';?>">
                <?=$this->formText($form->get('form_update')->get('fieldset_event_details')->get('city_global'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('city_global'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Which language will be primary at your Event?');?></small>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event_details')->get('city'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('city'))))?'has-errors':'';?>">
                <?=$this->formText($form->get('form_update')->get('fieldset_event_details')->get('city'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('city'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Which language will be primary at your Event?');?></small>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event')->get('event_group'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event')->get('event_group'))))?'has-errors':'';?>">
                <?=$this->formSelect($form->get('form_update')->get('fieldset_event')->get('event_group'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event')->get('event_group'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Is your Event as part of something bigger?');?></small>
            </div>
        </div>

    </div>

    <hr />

    <h3 class="display-5"><?=$this->translate("Your event external links");?></h3>

    <div class="container pt-2">
        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event_details')->get('event_map_external'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('event_map_external'))))?'has-errors':'';?>">
                <?=$this->formText($form->get('form_update')->get('fieldset_event_details')->get('event_map_external'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('event_map_external'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Is your Event as part of something bigger?');?></small>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event_details')->get('event_link_external'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('event_link_external'))))?'has-errors':'';?>">
                <?=$this->formText($form->get('form_update')->get('fieldset_event_details')->get('event_link_external'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event_details')->get('event_link_external'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Is your Event as part of something bigger?');?></small>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-2 py-2 px-0 pl-md-4 pr-md-5">
                <?=$this->formLabel($form->get('form_update')->get('fieldset_event')->get('status'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 <?=( ! empty($this->formElementErrors($form->get('form_update')->get('fieldset_event')->get('status'))))?'has-errors':'';?>">
                <?=$this->formSelect($form->get('form_update')->get('fieldset_event')->get('status'));?>
                <?=$this->formElementErrors($form->get('form_update')->get('fieldset_event')->get('status'));?>
            </div>
            <div class="col-12 col-md-5 py-2 px-0 pl-md-5">
                <small><?=$this->translate('Should you Event be visible in public?');?></small>
            </div>
        </div>

    </div>

    <hr />
    <div class="py-2 px-3 mb-2">
        <?=$this->formSubmit($form->get('submit'));?>
    </div>

    <div class="hidden">
        <?=$this->formElement($form->get('application_id'));?>
        <?=$this->formElement($form->get('csrf'));?>
    </div>

</div>

<?=$this->form()->closeTag();?>

