<?php if($form!==null): ?>
    <?php  $form->setAttribute('action', $this->url(sprintf('%s_%s_reset_password',$module,$submodule),array('uid'=>$uid)));?>
    <?php
    $form->prepare();

    ?>
    <div class="alert alert-info flash-messenger">
        <p>Only manual reset works</p>
    </div>
    <?php if(isset($formView,$formView[sprintf('%s_%s_reset_password',$module,$submodule)]['default'])):?>

        <?php foreach($formView[sprintf('%s_%s_reset_password',$module,$submodule)]['default'] as $fieldLocation=>$fieldLabel):?>
            <?php $element = $this->getObjectPathFromString($fieldLocation,$form); ?>
            <?php if($element->getAttribute('type')=='hidden'):?>
                <div class="hidden"><?php echo $this->formElement($element); ?></div>
                <?php echo $this->formElementErrors($element,array('class'=>'form-error')); ?>
                <?php continue; ?>
            <?php endif;?>
            <div class="col-xs-10">
                <div class="form-group">
                    <?php if(null!==$element&&$element->getOption('label')):?>
                        <div class="control-label col-xs-4 col-xs-offset-1">
                            <?php echo $this->formLabel($element); ?>
                            <?php if($element->getOption('label_options')): ?>
                                <?php $elementLabelOptions=$element->getOption('label_options');?>
                                <?php echo (is_array($elementLabelOptions)
                                    &&!empty($elementLabelOptions)
                                    &&isset($elementLabelOptions['required'])
                                    &&$elementLabelOptions['required']!==false)
                                    ?'<span class="color-red">*</span>':null; ?>
                            <?php endif; ?>
                        </div>
                    <?php endif;?>
                    <?php if($element->getAttribute('type')!=='submit'):?>
                    <div class="col-xs-7">
                        <?php echo $this->formElement($element); ?>
                        <?php echo $this->formElementErrors($element,array('class'=>'form-error')); ?>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="clearfix"></div>
        <?php endforeach; ?>
    <?php endif; ?>
        <div class="clearfix"></div>
        <div class="hidden">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>
<?php endif; ?>
