<div class="container">
    <div class="content-header" data-area-identifier="area-content_header">
        <?=$this->partial('content/area', array('area' => $area['content_header'],));?>
    </div><!-- /.content-header -->
    <div class="row">
        <div class="col-sm-3 content-sidebar sidebar-left" data-area-identifier="area-content_sidebar_left">
            <?=$this->partial('content/area', array('area' => $area['content_sidebar_left'],));?>
        </div><!-- /.content-sidebar -->
        <div class="col-sm-6 content-main" data-area-identifier="area-content_main">
            <?=$this->partial('content/area', array('area' => $area['content_main'],));?>
        </div><!-- /.content-main -->
        <div class="col-sm-3 content-sidebar sidebar-right" data-area-identifier="area-content_sidebar_right">
            <?=$this->partial('content/area', array('area' => $area['content_sidebar_right'],));?>
        </div><!-- /.content-sidebar -->
    </div><!-- /.row -->
</div><!-- /.container -->
<footer class="content-footer footer-main" data-area-identifier="area-footer_main">
    <?=$this->partial('content/area', array('area' => $area['footer_main'],));?>
</footer><!-- /.content-footer -->