<div class="app-container border-3">

    <div class="col-md-8 col-md-offset-2 p-4 p-md-5">
        <div class="app-container-header text-light text-center">
            <?=$this->partial("common-manager-partial::partial-header",['heading'=>$data_template_model['heading'],'data'=>null]);?>
        </div>

        <div class="">
            <?=$this->getFormAttached($forms,null,'form_create',true,$view_template_model['forms']['form_create']);?>
        </div>
    </div>

</div>