<?php

$form->prepare();
//var_dump($resources);die();
?>
<?=$this->partial("common-admin-partial::partial-header",['heading'=>$data_template_model['heading'],'data'=>$resources]);?>

<?php if(isset($messages)&&array_key_exists('error',$messages)):?>
    <?=$this->flashMessage($messages['error'],'error');?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('info',$messages)):?>
    <?=$this->flashMessage($messages['info'],'info');?>
<?php endif;?>

<?php if($resources): ?>

    <?php foreach($resources as $res):  ?>

        <?php if(array_key_exists('partial',$res['service_config'])): ?>
            <?=$this->partial($res['service_config']['partial'],['resource'=>$res]);?>
        <?php endif;?>

    <?php endforeach;?>

<?php endif; ?>
<?php


echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
