<div class="app-container app-template-create border-3">

    <div class="app-container-content p-4 p-md-5">
        <div class="app-container-header">
            <?=$this->partial("common-admin-partial::partial-header",['heading'=>$data_template_model['heading'],'data'=>null]);?>
        </div>

        <hr />

        <?php foreach($data_template_model['main']['table'] as $table):?>
        <div class="table-responsive">
            <table class="table table-hover table-sm" style="table-layout: fixed;">
                <thead class="thead-light">
                <tr>
                    <?php foreach($table['headers'] as $tableHeaderText):?>
                        <th><?=$this->escapeHtml($tableHeaderText);?></th>
                    <?php endforeach;?>
                </tr>
                </thead>
                <tbody>
                <?php if($paginator->count()===0): ?>
                    <tr>
                        <td COLSPAN="10"><i>No data items.</i></td>
                    </tr>
                <?php else:?>
                    <?php foreach($paginator as $item): ?>
                        <tr>
                            <?php if(array_key_exists('table_row',$view_template_model)):?>
                                <?=$this->partial(
                                    $view_template_model['table_row'],
                                    [
                                        'item'=>$item,
                                        'forms'=>(isset($forms))?$forms:null,
                                        'data_template_model'=>(isset($data_template_model))?$data_template_model:null,
                                    ]
                                );
                                ?>
                            <?php else: ?>
                                <?php foreach($table['rows'] as $tableRow):?>
                                    <?php if(array_key_exists('column',$tableRow)):?>
                                        <td><?=$this->escapeHtml($item->{$tableRow['column']});?></td>
                                    <?php elseif(array_key_exists('buttons',$tableRow)):?>
                                        <td><?=$this->displayLinkGroup($tableRow['buttons'],$item);?></td>
                                    <?php endif;?>
                                <?php endforeach;?>
                            <?php endif;?>
                        </tr>
                    <?php endforeach;?>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
        <?php endforeach;?>

        <?php
        echo $this->paginationControl($paginator,
            'Sliding',
            'common::pagination-control', array('route' => $data_template_model['route_name']));
        ?>

    </div>
</div>

