<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
<?php
    $children = $this->viewModel()->getCurrent()->getChildren();
    $child = $children[0];
    $title = (null!==$seo&&isset($seo[$page_uid]))?$seo[$page_uid]->getTitle():null;
    $description = (null!==$seo&&isset($seo[$page_uid]))?$seo[$page_uid]->getDescription():null;
    $keywords = (null!==$seo&&isset($seo[$page_uid]))?$seo[$page_uid]->getKeywords():null;
?>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="<?=$description;?>">
        <meta name="keywords" content="<?=$keywords;?>">
        <meta name="author" content="">
        <link rel="icon" href="assets/img/favicon.ico">
        <meta charset="utf-8">
        <?php echo $this->headTitle($title)->setSeparator(' - ')->setAutoEscape(false);?>

        <?php if($this->someVar==="admin"): ?><?php echo $this->headLink()
                ->appendStylesheet($this->basePath('assets/css/site.min.css'))
                ->appendStylesheet($this->basePath('assets/css/admin.min.css'))
            ;
            ?>
        <?php else: ?><?php echo $this->headLink()
                ->appendStylesheet($this->basePath('assets/css/site.min.css'))
            ;
            ?>
        <?php endif; ?>

        <?php if($this->someVar==="admin"): ?>
            <?php echo $this->headScript()
                ->prependFile($this->basePath('assets/js/SinglePageApplication.site.min.js'))
                ->prependFile($this->basePath('assets/js/SinglePageApplication.admin.min.js'))
                ->prependFile($this->basePath('assets/js/SinglePageApplication.jquery.min.js'))
                ->prependFile($this->basePath('assets/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('assets/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ; ?>
        <?php else: ?>
            <?php echo $this->headScript()
                ->prependFile($this->basePath('assets/js/SinglePageApplication.site.min.js'))
                ->prependFile($this->basePath('assets/js/SinglePageApplication.jquery.min.js'))
                ->prependFile($this->basePath('assets/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('assets/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ; ?>
        <?php endif; ?>

        
        <script type="text/javascript">
            WebFontConfig = {
                google: { families: ['Lato','Slabo','Roboto']
                }
            };
            (function() {
                var wf = document.createElement('script');
                wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
                    '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
                wf.type = 'text/javascript';
                wf.async = 'true';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(wf, s);
            })(document);

        </script>
    </head>
<?php
    $children = $this->viewModel()->getCurrent()->getChildren();
    $child = $children[0];
    $area = $child->getVariable('area');
?>
    <body id="" class="">
        <nav id="navbar-top" class="navbar navbar-default navbar-fixed-top" role="navigation">
            <?php if($this->someVar==="admin"): ?>
            <div id="frontbox-admin-menu-wrapper" class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-default">
                        <!--li class=""><a href="#">Editor</a></li-->
                        <li><a href="/singlepageapplication/page/create">Create Page</a></li>
                        <li><a class="menu-item-add-block" href="#">Add Block</a></li>
                        <li class="">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Developer <span class="caret"></span></a>
                            <ul class="dropdown-menu text-left">
                                <li class="dropdown-header">Show Paths</li>
                                <li><a href="#" class="menu-item menu-item-area" data-item-type="area">Area</a></li>
                                <li><a href="#" class="menu-item menu-item-block" data-item-type="block">Block</a></li>
                                <li><a href="#" class="menu-item menu-item-content" data-item-type="content">Content</a></li>
                            </ul>
                        </li>
                        <li class="">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Editor <span class="caret"></span></a>
                            <ul class="dropdown-menu text-left">
                                <li><a href="/singlepageapplication/page/create" class="menu-item menu-item-area" data-item-type="area">Create Page</a></li>
                                <li class="dropdown-header">Current Page</li>
                                <li><a href="#" class="menu-item menu-item-area" data-item-type="area">Area Helper</a></li>
                                <li><a href="#" class="menu-item menu-item-content" data-item-type="content">Add Content</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <?php endif; ?>
            <div class="container navbar-top">
                <div class="col-md-6">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-user" aria-expanded="false" aria-controls="navbar-user">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand" href="#" data-area-identifier="area-001">
                        <div data-block-identifier="block-001">
                            <a class="navbar-brand" href="#" data-content-identifier="content-001">
                                <img src="/assets/img/logo/logo-ecancer-dark.png" alt="" />
                                <div class="clearfix"></div>
                            </a>
                        </div>
                        <div data-block-identifier="block-002">
                            <p data-content-identifier="content-002">the leading oncology channel</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div id="navbar-user" class="navbar-collapse collapse" data-area-identifier="area-002">
                        <ul class="nav navbar-nav navbar-right" data-block-identifier="block-003">
                            <li class="menu-item" data-content-identifier="content-003"><a href="#">ecancerpatient</a></li>
                            <li class="menu-item administrator" data-content-identifier="content-003"><a href="<?php echo $this->url('authentication_login');?>">Administrator</a></li>
                            <li class="menu-item-inverse" data-content-identifier="content-004"><a href="#">English</a></li>
                            <li class="menu-item-icon" data-content-identifier="content-005" style="background-color:#6e757f;" >
                                <a style="width:100%;height:100%;display:block;" href="./">
                                    <span style="color:#ccf131" class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                </a>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
            <div class="container navbar-fixed-top-bottom">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="navbar" class="collapse navbar-collapse menu-main" data-area-identifier="area-003">
                    <ul class="nav navbar-nav" data-block-identifier="block-004">
                        <li data-content-identifier="content-006"><a href="/">Home</a></li>
                        <li data-content-identifier="content-007"><a href="/journal">Journal</a></li>
                        <li data-content-identifier="content-008"><a href="/video">Video</a></li>
                        <li data-content-identifier="content-009"><a href="/news">News</a></li>
                        <li data-content-identifier="content-010"><a href="/conferences">Conferences</a></li>
                        <li data-content-identifier="content-011"><a href="/e-learning">E-Learning</a></li>
                        <li data-content-identifier="content-012"><a href="/projects">Projects</a></li>
                        <!--
                        <li data-content-identifier="content-013" class="navbar-right navbar-item-search">
                            <form class="navbar-form">
                                <div class="form-group">
                                    <input type="text" placeholder="Search" class="input-xs form-control">
                                </div>
                                <button type="submit input-xs">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </button>
                            </form>
                        </li>
                        -->
                    </ul>
                </div><!--/.nav-collapse -->
                <?php
                //echo $this->navigation('main_menu')->setAcl($this->acl)->setRole($this->role)->menu();
                ?>
            </div>
        </nav>
        <div id="content">
            <?php echo $this->content; ?>
        </div>
        <!-- Begin FOOTER: -->
        <div class="clearfix hr-20"></div>
        <div class="clearfix hr-20"></div>
        <div class="clearfix hr-20"></div>

        <!-- Begin FOOTER: -->
        <div  class="footer" data-area-identifier="area-008">
            <div  class="container" data-block-identifier="block-012">
                <div class="col-sm-2 col-sm-offset-1">
                    <ul class="list-group">
                        <li class="list-group-item-heading">Disease areas</li>
                        <li class="list-group-item">Cras justo odio</li>
                        <li class="list-group-item">Dapibus ac facilisis in</li>
                        <li class="list-group-item">Morbi leo risus</li>
                        <li class="list-group-item">Porta ac consectetur ac</li>
                        <li class="list-group-item">Vestibulum at eros</li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <ul class="list-group">
                        <li class="list-group-item-heading">Patient Care</li>
                        <li class="list-group-item">Dapibus ac facilisis in</li>
                        <li class="list-group-item">Morbi leo risus</li>
                        <li class="list-group-item">Porta ac consectetur ac</li>
                        <li class="list-group-item">Vestibulum at eros</li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <ul class="list-group">
                        <li class="list-group-item-heading">Policy</li>
                        <li class="list-group-item">Dapibus ac facilisis in</li>
                        <li class="list-group-item">Morbi leo risus</li>
                        <li class="list-group-item">Porta ac consectetur ac</li>
                        <li class="list-group-item">Vestibulum at eros</li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <ul class="list-group">
                        <li class="list-group-item-heading">Prevention & Screening</li>
                        <li class="list-group-item">Dapibus ac facilisis in</li>
                        <li class="list-group-item">Morbi leo risus</li>
                        <li class="list-group-item">Porta ac consectetur ac</li>
                        <li class="list-group-item">Vestibulum at eros</li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <ul class="list-group">
                        <li class="list-group-item-heading">Treatments</li>
                        <li class="list-group-item">Dapibus ac facilisis in</li>
                        <li class="list-group-item">Morbi leo risus</li>
                        <li class="list-group-item">Porta ac consectetur ac</li>
                        <li class="list-group-item">Vestibulum at eros</li>
                    </ul>
                </div>
            </div>

            <div class="clearfix hr-20"></div>
            <section>
                <div  class="container" data-block-identifier="block-012">
                    <div class="col-sm-2">
                        <img src="/assets/img/logo/logo-ieo.gif" alt="" class="img-responsive" />
                    </div>
                    <div class="col-sm-2">
                        <img src="/assets/img/logo/logo-ecco.png" alt="" class="img-responsive" />
                    </div>
                    <div class="col-sm-2">
                        <img src="/assets/img/logo/logo-fundazione_veronesi.png" alt="" class="img-responsive" />
                    </div>
                    <div class="col-sm-2">
                        <img src="/assets/img/logo/logo-fundazione_ieo.png" alt="" class="img-responsive" />
                    </div>
                    <div class="col-sm-2">
                        <img src="/assets/img/logo/logo-swiss_bridge.png" alt="" class="img-responsive" />
                    </div>
                    <div class="col-sm-2">
                        <img src="/assets/img/logo/logo-swiss_bridge.png" alt="" class="img-responsive" />
                    </div>
                </div>
                <div class="clearfix hr-20"></div>
                <div class="clearfix hr-20"></div>
            </section>
            <section id="footer-final">
                <div class="container">
                    <div class="col-sm-9">
                        <p>Place sticky footer content here.</p>
                    </div>
                    <div class="col-sm-3">
                        <img src="/assets/img/logo/logo-ci.png" alt="" class="img-responsive pull-right" />
                    </div>
                </div>
            </section>
        </div>
        <?php echo $this->inlineScript() ?>
        <script type="text/javascript">
            $(window).scroll(function() {
                if ($(document).scrollTop() > 0) {
                    $('.navbar').addClass('scroll');
                    $('main').addClass('scroll');
                } else {
                    $('.navbar').removeClass('scroll');
                    $('main').removeClass('scroll');
                }
            });
            <?php if($this->someVar==="admin"): ?>
            $( document ).ready(function() {
                objDeveloper.setup();
                objEditor.setup();
            });
            <?php endif; ?>
        </script>
        <div class="no-display"></div>
        <div id="menu-editor-blocks-side">
            <button class="btn btn-success">Save</button>
            <button class="btn btn-danger">Cancel</button>
            <h3>Add Blocks</h3>
            <div class="wrapper">
                <p>In order to add new block drag one of the blocks below and drop it into any area.</p>
                <div class="col-sm-6 drag-item">
                    <span>Html</span>
                    <span class="no-display"><input type="hidden" class="block-type" value="html" /></span>
                </div>
                <div class="col-sm-6 drag-item">
                    <span>Image</span>
                    <span class="no-display"><input type="hidden" class="block-type" value="image" /></span>
                </div>
                <div class="col-sm-6 drag-item">
                    <span>Api</span>
                    <span class="no-display"><input type="hidden" class="block-type" value="api" /></span>
                </div>
                <div class="col-sm-6 drag-item">
                    <span>Menu</span>
                    <span class="no-display"><input type="hidden" class="block-type" value="menu" /></span>
                </div>
                <div class="col-sm-6 drag-item">
                    <span>Carousel</span>
                    <span class="no-display"><input type="hidden" class="block-type" value="carousel" /></span>
                </div>
                <div class="col-sm-6 drag-item">
                    <span>Form</span>
                    <span class="no-display"><input type="hidden" class="block-type" value="form" /></span>
                </div>
            </div>
        </div>
    </body>
</html>