<?php $this->headTitle('Home'); ?>

<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">zend-expressive</span></h1>
    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/zendframework/zend-expressive-skeleton" target="_blank">zend-expressive skeleton application</a>.
        This skeleton can serve as a simple starting point for you to begin building your application.
    </p>
    <p>
        Expressive builds on zend-stratigility to provide a minimalist PSR-7 middleware framework for PHP.
    </p>
</div>
