<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/pagination.css'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('flags/famfamfam-flags.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/scroll-top.js'))
            ->prependFile($this->basePath('js/toggle-display.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-ui.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ;

        ?>

        <link rel="stylesheet" type="text/css" href="//cloud.github.com/downloads/lafeber/world-flags-sprite/flags16.css"/>
        <script>
                objScrollTop.setup();
        </script>
        <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
        <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>
    </head>
    <body>
        <div class="container main">

             <?php echo $this->content; ?>

        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        
        <footer class="footer" style="background-color:#212121">
            <div id="scroll-top-button-wrapper" style="display:none;">
                 <span class="glyphicon glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
            </div>
            <div class="container form-action hidden">
                 <p class="text-muted">Changes detected &nbsp;&nbsp;<button class="btn btn-success">Save Changes</button>&nbsp;&nbsp;&nbsp;<button class="btn btn-danger">Ignore Changes</button></p>
            </div>
        </footer>
    </body>
</html>
