<?php foreach($heading as $header): ?>
    <div class="d-block pb-2 mb-3 ">
        <?php
            if(array_key_exists('html_tag',$header) && array_key_exists('text',$header)):
        ?>
            <?=sprintf(
                '<%1$s>%2$s%3$s</%1$s>',
                $header['html_tag'],
                $this->translate($header['text']),
                (array_key_exists('buttons',$header))?$this->displayLinkGroup($header['buttons'],$data):null
            );?>
        <?php
            elseif(array_key_exists('buttons',$header)):
        ?>
            <?=$this->displayLinkGroup($header['buttons'],$data);?>
        <?php endif; ?>
    </div>
<?php endforeach; ?>