<?php if(isset($messages)&&array_key_exists('error',$messages)):?>
    <?=$this->flashMessage($messages['error'],'error');?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('info',$messages)):?>
    <?=$this->flashMessage($messages['info'],'info');?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('success',$messages)):?>
    <?=$this->flashMessage($messages['success'],'success');?>
<?php endif;?>
<?php
$forms['form_login']->prepare();
?>


<div class="col-12 m-auto col-lg-8 px-4" role="main">

    <div class="app-container app-register border-3">

        <div class="app-container-header text-center">
            <div class="text-center pb-2 mb-3 mt-5">
                <h1 class="display-1"><?=$this->translate("Sign in to Art13.eu");?></h1>
            </div>
        </div>
        <div class="app-container-content px-4 py-1 p-md-5 py-md-1">

            <?=$this->form()->openTag($forms['form_login']);?>

            <div class="form-container ">
                <?=$this->formElementErrors($forms['form_login']->get('security'));?>
                <div class="container pt-2">
                    <div class="row">
                        <div class="col-12 py-2 px-0">
                            <label for="form_create[fieldset_credentials_password][password]"><?=$this->translate('Registered email');?></label>
                            <?=$this->formInput($forms['form_login']->get('form_login')->get('fieldset_credentials')->get('email'));?>
                            <?=$this->formElementErrors($forms['form_login']->get('form_login')->get('fieldset_credentials')->get('email'));?>
                        </div>
                        <div class="col-12 py-2 px-0">
                            <label for="form_create[fieldset_credentials_password][password_confirm]"><?=$this->translate('Password');?></label>
                            <?=$this->formInput($forms['form_login']->get('form_login')->get('fieldset_credentials')->get('password'));?>
                            <?=$this->formElementErrors($forms['form_login']->get('form_login')->get('fieldset_credentials')->get('password'));?>
                        </div>
                        <div class="checkbox mt-2 d-none">
                            <?=$this->formCheckbox($forms['form_login']->get('form_login')->get('fieldset_rememberme')->get('remember_me'));?>
                            <?=$this->formLabel($forms['form_login']->get('form_login')->get('fieldset_rememberme')->get('remember_me'));?>
                        </div>
                    </div>
                </div>

                <hr>

                <div class="py-2 px-0 mb-2">
                    <?=$this->formSubmit($forms['form_login']->get('send'));?>
                </div>

                <div class="hidden">
                    <input name="application_id" value="" type="hidden">
                    <?=$this->formElement($forms['form_login']->get('security'));?>
                </div>
            </div>

            <?=$this->form()->closeTag();?>

        </div>
    </div>
</div>