<?php if(isset($messages)&&array_key_exists('error',$messages)):?>
    <?=$this->flashMessage($messages['error'],'error');?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('info',$messages)):?>
    <?=$this->flashMessage($messages['info'],'info');?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('success',$messages)):?>
    <?=$this->flashMessage($messages['success'],'success');?>
<?php endif;?>
<?php
$forms['form_request']->prepare();
?>
    <div class="row">
        <div class="col-4 offset-4 pb-3 border-bottom">
            <?=$this->form()->openTag($forms['form_request']);?>
                <img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
                <h1 class="h3 mb-3 font-weight-normal">Request Password Change</h1>
                <label for="inputEmail" class="sr-only">Email address</label>
                <?=$this->formInput($forms['form_request']->get('form_request')->get('fieldset_credentials')->get('email'));?>
                <?=$this->formElementErrors($forms['form_request']->get('form_request')->get('fieldset_credentials')->get('email'));?>
            <?=$this->formElement($forms['form_request']->get('security'));?>
            <?=$this->formElementErrors($forms['form_request']->get('security'));?>
            <?=$this->formSubmit($forms['form_request']->get('send'));?>
            <?=$this->form()->closeTag();?>
        </div>
        <div class="col-2 offset-4 mt-1">
            <a href="<?=$this->url('spa.auth.login');?>">Login</a>
        </div>
        <div class="col-2 text-right mt-1">
            <a href="<?=$this->url('spa.auth.reset');?>">I have the code</a>
        </div>
    </div>

