<div class="container slide-home" data-area-identifier="area-004">
    <?php
    if($flash_messages->getMessages()):
        echo '<pre>';
        print_r($flash_messages->getMessages());
        echo '</pre>';
    endif;
    ?>
    <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-md-8">

        </div>
    </div>
    <div class="clearfix hr-20" data-block-identifier="#"></div>
</div>