<div class="container slide-home" data-area-identifier="area-004">
    <div class="row">
        <div class="col-md-3" data-area-identifier="area-col-left">

        </div>
        <div class="col-md-6" data-area-identifier="area-col-main">

        </div>
        <div class="col-md-3" data-area-identifier="area-col-right">

        </div>
    </div>
    <div class="clearfix hr-20" data-block-identifier="#"></div>
</div>